In [1]:
import requests
import pandas as pd
import numpy as np
from careerjet_api_client import CareerjetAPIClient
pd.set_option('display.max_colwidth', -1) #expand full columns

cj  =  CareerjetAPIClient("en_US")
result_json = cj.search({
                          'location'    : 'Texas',
                          'keywords'    : 'Data Analyst',
                          'affid'       : '#customaffid',
                          'user_ip'     : '#customuserip',
                          'url'         : 'https://www.careerjet.com/search/jobs?s=data+analyst&l=Bay+Area',
                          'user_agent'  : 'Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0',
                          'page': '1'
                        });
df = pd.DataFrame(result_json['jobs'])
a = df.index.values.tolist() 
df = df.drop(a)
df

Empty DataFrame
Columns: [company, date, description, locations, salary, salary_currency_code, salary_max, salary_min, salary_type, site, title, url]
Index: []

In [2]:
for i in range(1,5):

    cj  =  CareerjetAPIClient("en_US")
    result_json = cj.search({
                            'location'    : 'Texas',
                            'keywords'    : 'Data Analyst',
                            'affid'       : 'ac81902ea6025bafcfbdb8c515879b32',
                            'user_ip'     : '67.180.142.36',
                            'url'         : 'https://www.careerjet.com/search/jobs?s=data+analyst&l=Bay+Area',
                            'user_agent'  : 'Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0',
                            'page': i
                          });
    df2 = pd.DataFrame(result_json['jobs'])#converts json into data frame
    
    dfList = [df,df2]# df is a empty data frame with structure. 
    df = pd.concat(dfList,ignore_index=True)# concatinate both the DF
    
    labels = df2.index.values.tolist() 
    df2 = df2.drop(labels)#deleting the Df created
df

/Users/antonypaulson/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:16: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  app.launch_new_instance()

,company,date,description,locations,salary,salary_currency_code,salary_max,salary_min,salary_type,site,title,url
0,Alamo Drafthouse Cinemas,"Fri, 30 Nov 2018 08:10:25 GMT","Benefit <b>Analyst</b> position performs the administration of all benefits and retirement programs, including medical, dental... compliance team to ensure accurate carrier feeds and rate table set up. Runs Quarterly Audits of benefit related <b>data</b> Processes...","Austin, TX",,NaN,NaN,NaN,NaN,,Benefits Analyst,http://jobviewtrack.com/en-us/job-1d4f416f480a0a084e005343290f0f0b1c53006a281d4b47445e59662d0b4911460a1c126f5555174c5a/14b492f081cdb7f15be85ebe0ab90838.html?affid=ac81902ea6025bafcfbdb8c515879b32
1,Direct Energy,"Thu, 13 Dec 2018 08:22:24 GMT","Senior <b>Data</b> Systems <b>Analyst</b> Location: Greenway Plaza, Houston, Texas Job type: Permanent Direct Energy... <b>Data</b> <b>Analyst</b> will help drive the advancement of cutting-edge analysis, modelling, and recommendation algorithms. In...","Houston, TX",,NaN,NaN,NaN,NaN,,Senior Data Systems Analyst,http://jobviewtrack.com/en-us/job-4c18417e480a0601555464021c004e260b4118111a0728785843440b1d4e740d53170d0c1d47244e150410005e29794c59054f2f49154c1a1b156c341c53000d04000a6a534c411d1c1a2527450d010e1c47244e150410005e2a0f1c1c5556/84b6a31a6a269ca6f997f4e7def7228e.html?affid=ac81902ea6025bafcfbdb8c515879b32
2,The Hunt Corporation,"Thu, 13 Dec 2018 08:58:58 GMT","we are,down to not only delivering a better world [ but working to ma AECOM Project Controls <b>Analyst</b> II in Austin, Texas United States of America... and methodologies. Works with the project team to develop and update project schedules. Collects <b>data</b> and produces an initial...","Austin, TX",$100000 per year,USD,100000,100000,Y,,Project Controls Analyst II,http://jobviewtrack.com/en-us/job-484d417d5f0b050b44000020070f1a150a4c0748281d4b47445e59663f1c481e45001c412d080b5406070500287b4f4247010c1a07354e0204181d1367611a09050a595f3f7d5f0b050b4400215158565655/1c4a5837439a3551788b39d7fc93d68e.html?affid=ac81902ea6025bafcfbdb8c515879b32
3,Ryder Logistics & Transportation,"Thu, 13 Dec 2018 08:52:22 GMT","Time (4) Travel Requirements 10-20% Position Code 0673 Position Description The Logistics <b>Analyst</b> is responsible... techniques, and working with images and text Advanced Level Skills in MS Excel such as working with formulas, <b>data</b> tables, pivot...","Fort Worth, TX",,NaN,NaN,NaN,NaN,,Logistics Analyst,http://jobviewtrack.com/en-us/job-484a41614203061d531d4310482000060959071c6b32444a51545e106d22481349101c080d14641245585a43/c5f1a1895a4bd1b7cf718e890230b49b.html?affid=ac81902ea6025bafcfbdb8c515879b32
4,Maxim Government Services,"Thu, 06 Dec 2018 08:53:09 GMT",of Program Managers and Behavior Technicians. Write reports with graphed <b>data</b> Assist with training staff in the office...,"Houston, TX",,NaN,NaN,NaN,NaN,,Board Certified Behavior Analyst BCBA,http://jobviewtrack.com/en-us/job-1a12416f6e262e4e651b41110c412d0217541d0e00164e0b7f4845051907480600220600021e1654762a0612584f1d6e48161b07411d450748230b0f04561d071b536b455c4154171b6c651148021e08011545611a09050a595f1d6f6e262e6c64115217010707020100360d01125c42525f0d25010f4b0d53176a230b0f04561d071b536b455c4154171b6f1545115251/6652af1a4f32fd4e84a03f52abee1a44.html?affid=ac81902ea6025bafcfbdb8c515879b32
5,Paccar,"Wed, 12 Dec 2018 08:36:21 GMT","the Class of the Industry. Requisition Summary Peterbilt Motors Company, a PACCAR Company, has an opening for a <b>Data</b>... <b>Analyst</b> Intern to add to our IT Team in Denton, Texas for Summer 2019. Job Functions / Responsibilities This position...","Denton, TX",,NaN,NaN,NaN,NaN,,IT Data Analyst Intern - Summer 2019 Job,http://jobviewtrack.com/en-us/job-1a4841694c100e4e661a410f11121a472c4e000d1b1d2878484040011d4e6e1a54061a0f4e2e3122271d041e4f591d6c430503175400002a06150b150b2230091d120a6a534c411d1c1a2527550e05041c472c4e000d1b1d2b190d141b5d/554317ca9a128720def2a168abe27089.html?affid=ac81902ea6025bafcfbdb8c515879b32
6,CPS Energy,"Wed, 12 Dec 2018 07:38:03 GMT","with <b>Data</b> Science / <b>Data</b> <b>Analyst</b> and their associated tools. Experience in Test Driven Development (TDD). Proficiency... opportunity to design, develop, and unit test new or existing <b>Data</b> Integration solutions. GRADE: 16 DEADLINE TO APPLY: Monday...","San Antonio, TX",,NaN,NaN,NaN,NaN,,Data Engineer,http://jobviewtrack.com/en-us/job-1b1341694c100e4e621a470a06040b1567651a0f001d4f4e4f2f69051b0f264611575e54/90892ae46aded8abcfe4233390fc136c.html?affid=ac81902ea6025bafcfbdb8c515879b32
7,NTT Data,"Thu, 13 Dec 2018 06:38:41 GMT","Req ID: 37437 At NTT <b>DATA</b> Services, we know that with the right people on board, anything is possible. The quality... and personally, we ensure a bright future for NTT <b>DATA</b> Services and for the people who work here. NTT <b>DATA</b> Services currently seeks...","Plano, TX",,NaN,NaN,NaN,NaN,,Clinical-Technical Help Desk Support Analyst,http://jobviewtrack.com/en-us/job-1919416548081f4e6311530848350b040d4e1d0b081f0a78485d5d0b1d1a253c450f18412a02164b543b1c035a444f592f2c0a02575464061b0a4e260b4118111a07287f584e450a060d461800301d111e0817545429071246524e592f2c0a02575464061b0a4e3300431c0600104b473c1f1c57575e/57dd18864359cd933a9dd925d258b34b.html?affid=ac81902ea6025bafcfbdb8c515879b32
8,Bansar Technologies Inc,"Fri, 16 Nov 2018 08:14:29 GMT","<b>Data</b> analysis, <b>Data</b> warehouse solutions, SQL, PL/SQL, Reports/Dashboards, <b>Data</b> visualization tools/tableau, <b>Data</b>...","Austin, TX",,NaN,NaN,NaN,NaN,,Business Data Analyst,http://jobviewtrack.com/en-us/job-4f1f41694c100e4e661a410f11121a65244e150410005e297f585e0d010b540700220600021e1654542c08074b297f585e0d010b540722211d12070900530748281d4b47445e59655d5e104c12/975c852d5ee3c69118c9e27d142364b0.html?affid=ac81902ea6025bafcfbdb8c515879b32
9,Bansar Technologies Inc,"Sun, 11 Nov 2018 08:52:22 GMT","<b>Data</b> Architecture, <b>Data</b> Governance, <b>Data</b> Quality, <b>Data</b> Profiling, <b>Data</b> Integration, <b>Data</b> Modeling, Oracle/SQL Server...","Austin, TX",,NaN,NaN,NaN,NaN,,Data Architect/Data Analyst,http://jobviewtrack.com/en-us/job-4f4e41694c100e4e6606430b01150b04112230091d120a6a534c411d1c1a2535520000081a0206547629071246524e592f200e1a467512535f595c/5293c054e9b6ff312bf0e545b45c775f.html?affid=ac81902ea6025bafcfbdb8c515879b32
10,,"Sun, 04 Nov 2018 08:40:47 GMT","laws and policies. Oversees collection of, analyzes, researches, documents, interprets, audits and reports financial <b>data</b>... Characteristics: This is the third in a series of four professional financial <b>analyst</b>-related job classifications within the Finance...","Austin, TX",,NaN,NaN,NaN,NaN,,Financial Analyst Lead,http://jobviewtrack.com/en-us/job-4918416148050b4e661a410f11121a6523491a090710434a512f61010e0a25354e0204181d1367661d06081d49425c410d25010f4b0d531769535e505d12/b4b9d6518853b7708d9883011f0ebc95.html?affid=ac81902ea6025bafcfbdb8c515879b32
11,Bansar Technologies Inc,"Mon, 05 Nov 2018 08:31:30 GMT","MDM, <b>Data</b> Quality, <b>Data</b> Governance, <b>Data</b> Profiling, <b>Data</b> Integration, Metadata, Oracle/SQL Server, Preferred Skills...","Austin, TX",,NaN,NaN,NaN,NaN,,Senior Data Analyst,http://jobviewtrack.com/en-us/job-1d1f41694c100e4e661a410f11121a6536451a0106010a6f5c594c442e00461859101c633d020b491b1a49374b5f5c2f6c0a0e025e0754613b04000e0a52755a59441219/e731dd53e53b2f0dc8a73b7e14293dc4.html?affid=ac81902ea6025bafcfbdb8c515879b32
12,Targetbase,"Thu, 13 Dec 2018 08:21:38 GMT","Location: Irving, TX Department: Technology Description JOB SCOPE & PURPOSE The Business <b>Analyst</b> creates..., systems, third party vendors, and potential <b>data</b> sources Assist in shaping statements of work and lead client requirements...","Irving, TX",,NaN,NaN,NaN,NaN,,Business Analyst,http://jobviewtrack.com/en-us/job-4c1b416f5817060042075343290f0f0b1c53006a281d4b47445e59662d1b541d4e061b126f555411405b/45f8e6c4843306b045c1f32b254e3be2.html?affid=ac81902ea6025bafcfbdb8c515879b32
13,Targetbase,"Thu, 13 Dec 2018 08:20:15 GMT",pace. We are a <b>data</b>-driven marketing company that thrives on curious performers that enjoy deadlines and fun... The Jr. Financial <b>Analyst</b> is responsible for working with the CFO and Sr. Financial <b>Analyst</b> in running business operations...,"Irving, TX",,NaN,NaN,NaN,NaN,,"Financial Analyst, Jr",http://jobviewtrack.com/en-us/job-4f1841675f44290749154e0001000247244e150410005e297b444305010d4e154c43290f0f0b1c53006a23010a6a534c411d1c1a25354e0204181d1367661d06081d49425c412c565e5f1347/7f29aa140df358c273aa268b81002186.html?affid=ac81902ea6025bafcfbdb8c515879b32
14,Targetbase,"Thu, 13 Dec 2018 08:13:42 GMT","Location: Irving, TX Department: SBA - Dallas Description About Targetbase As a <b>data</b>-driven, strategic..., which improves consumer engagement and drives a more profitable outcome for clients. The <b>Analyst</b> within Analytics provides...","Irving, TX",,NaN,NaN,NaN,NaN,,"Analyst, Analytics",http://jobviewtrack.com/en-us/job-121f416c43050317531d4310482000060959071c6b32444a51545e106d2f49154c1a1c080d14641245595d40/1c8a6c2a4e12081438b892eca6d956dd.html?affid=ac81902ea6025bafcfbdb8c515879b32
15,NTT Data,"Wed, 21 Nov 2018 08:06:44 GMT","a Senior Business <b>Data</b> <b>Analyst</b> to join our team in Austin, TX. Candidates local to Austin, TX are strongly preferred. The...Req ID: 36046 At NTT <b>DATA</b> Services, we know that with the right people on board, anything is possible. The quality...","Austin, TX",,NaN,NaN,NaN,NaN,,Senior Business Data Analyst,http://jobviewtrack.com/en-us/job-491e417e480a0601555462161b08000216535429071246524e592f370a004e1b52432c001a0645611a09050a595f3f6f5817060042075343290f0f0b1c5300482d125e4a3f6f5817060042075343290f0f0b1c53006a2d125e4a1d6c430503175400215158565655/90544e861ae68a377b7a78f885b404f1.html?affid=ac81902ea6025bafcfbdb8c515879b32
16,NTT Data,"Wed, 21 Nov 2018 07:51:26 GMT","a Senior Business <b>Data</b> <b>Analyst</b> to join our team in Austin, TX. Candidates local to Austin, TX are strongly preferred. The...Req ID: 36046 At NTT <b>DATA</b> Services, we know that with the right people on board, anything is possible. The quality...","Austin, TX",,NaN,NaN,NaN,NaN,,Senior Business Data Analyst,http://jobviewtrack.com/en-us/job-491e417e480a0601555462161b08000216535429071246524e592f370a004e1b52432c001a0645611a09050a595f3f6f5817060042075343290f0f0b1c5300482d125e4a3f6f5817060042075343290f0f0b1c53006a2d125e4a1d6c430503175400215158565655/60fbf3d7f6ed89b700b32b027bfbdb85.html?affid=ac81902ea6025bafcfbdb8c515879b32
17,CyberCoders,"Thu, 13 Dec 2018 08:42:26 GMT",This position is open as of 12/11/2018. Senior <b>Data</b> <b>Analyst</b> - Video Streaming If you are a Senior <b>Data</b> <b>Analyst</b>... experiences. We are seeking an exceptional <b>data</b> <b>analyst</b>/<b>data</b> scientist to synthesize and leverage <b>data</b> to provide us with timely...,"Austin, TX",$120000 - 160000 per year,USD,160000,120000,Y,,Senior Data Analyst,http://jobviewtrack.com/en-us/job-1d13417e480a0601555464021c004e260b4118111a07286f5c594c442e00461859101c633d020b491b1a4932444a51545e106d3d421a490c1a412a0611417629071246524e592c565f591f46/1d42686ce46ee3fd51eb15c558cd6572.html?affid=ac81902ea6025bafcfbdb8c515879b32
18,Robert Half,"Thu, 13 Dec 2018 08:11:34 GMT","Description A global manufacturer in Plano is looking for a Financial <b>Data</b> <b>Analyst</b> who will be responsible for the.... Works closely with the FFS DA <b>Analyst</b> team and Sales Reporting Manager, Master <b>Data</b>, and our third party <b>data</b> collection...","Plano, TX",$18 - 19 per hour,USD,19,18,H,,Financial Data Analyst,http://jobviewtrack.com/en-us/job-4b4e416b440a0e00441d410f48250f1304003506081f5358492f6b0d010f4917490204412f09044c0d1b1d716e4a494c0d25010f4b0d53176a270709044e1701081f0a6f5c594c662e00461859101c605c56561844/01cc7b4c0267710c32cd3f6fbdc97eb7.html?affid=ac81902ea6025bafcfbdb8c515879b32
19,Robert Half,"Thu, 13 Dec 2018 08:10:08 GMT",Ref ID: 04010-0010746354 Classification: Business <b>Analyst</b> Compensation: DOE We are seeking a <b>Data</b> <b>Analyst</b>.... They have way too many manual processes. *<b>data</b> automation *<b>data</b> modeling *<b>data</b> manipulation *<b>data</b> mapping *reporting *<b>data</b> cleansing...,"Dallas, TX",,NaN,NaN,NaN,NaN,,Data Reporting Analyst,http://jobviewtrack.com/en-us/job-1f4941694c100e4e7511500c1a15070902003506081f5358492f69051b0f07354e0204181d136772111806015e42534a0d25010f4b0d53176a250f130400260d191c585f54434a662e00461859101c605c575c1543/13068bec6d53419ebe13104b4688fb95.html?affid=ac81902ea6025bafcfbdb8c515879b32
20,Wits Solutions Inc,"Thu, 13 Dec 2018 07:49:00 GMT","Role: <b>Data</b> Scientist - Senior <b>Analyst</b> Consultant Location: Irving, Irving Duration: 5 months Please send...","Irving, TX",,NaN,NaN,NaN,NaN,,Data Scientist - Senior Analyst Consultant,http://jobviewtrack.com/en-us/job-494a417e480a0601555464021c004e260b4118111a07286f5c594c442e00461859101c633d020b491b1a4932444a51545e106d3d421a490c1a413d040c451a1c00005e29794c59054f3d441d450d1c081d13641245595d40/d99deef90c5eee6a2dea1d3d79dc0b95.html?affid=ac81902ea6025bafcfbdb8c515879b32
21,ReqRoute,"Thu, 13 Dec 2018 06:52:35 GMT",BI <b>data</b> <b>Analyst</b> Position Type (Permanent) At this point client is not willing to sponsor visas. Experience... with BI tools & <b>Data</b> Warehousing • Proficient in writing SQL Good Communication and Presentation skills Coordinating...,"Plano, TX",,NaN,NaN,NaN,NaN,,9063 BI Data Analyst,http://jobviewtrack.com/en-us/job-124a41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16471853/04589cac227c6607a365c5ed6cc37f3e.html?affid=ac81902ea6025bafcfbdb8c515879b32
22,St Joseph Health System,"Thu, 13 Dec 2018 06:20:01 GMT","and interpret <b>data</b> on operational performance, and create reports and benchmarks to provide in-depth <b>data</b> analytics to support the... CHP strategic objectives. It requires the analysis and translation of <b>data</b> into meaningful information and knowledge...","Lubbock, TX",,NaN,NaN,NaN,NaN,,Clinical Data Analyst,http://jobviewtrack.com/en-us/job-4e4a416e410d010744154c432c001a0645611a09050a595f3f694c100e4e661a410f11121a65264c1d0600104b471d6c43050317540022200408000e064118482d125e4a3f6c430503175400215159535d52/37d54198098f1121c00e1b44fb011601.html?affid=ac81902ea6025bafcfbdb8c515879b32
23,Robert Half,"Thu, 13 Dec 2018 04:58:15 GMT",Description Robert Half Technology's new REMOTE position for <b>Data</b> <b>Analyst</b> needs someone who provides comprehensive... support - 2 years experience working in a sales support environment - Must be <b>data</b> driven and good with analytics...,"Dallas, TX",$70000 - 75000 per year,USD,75000,70000,Y,,Data Analyst,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/01907084254c2e9f47edc3eff67468ca.html?affid=ac81902ea6025bafcfbdb8c515879b32
24,Dow,"Thu, 13 Dec 2018 04:09:26 GMT","The Dow Chemical Company has an exciting opportunity for a Production <b>Data</b> <b>Analyst</b> in Texas City, Texas. Purpose... in Diamond Systems. Production <b>Data</b> <b>Analyst</b>’s (PDA) primary responsibility is to reconcile and close production/period...","Texas City, TX",,NaN,NaN,NaN,NaN,,Production Data Analyst,http://jobviewtrack.com/en-us/job-491d41694c100e4e661a410f11121a6535521b0c1c105e4252430d25010f4b0d53176a2000060959071c6b23584459584e100601497664021c006f5554154051/70f7e5d64607db11f9e713a86c46b12c.html?affid=ac81902ea6025bafcfbdb8c515879b32
25,Atrilogy,"Thu, 13 Dec 2018 03:31:11 GMT","Atrilogy's direct Client is looking for a BI <b>Data</b> <b>Analyst</b>​ in Westlake, TX on a 6+ month Contract. The BI <b>Data</b> <b>Analyst</b>... and maintaining Business Intelligence capability for the client. The <b>Data</b> <b>Analyst</b> is responsible for partnering with the various...","Westlake, TX",,NaN,NaN,NaN,NaN,,BI Data Analyst,http://jobviewtrack.com/en-us/job-1b1c41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16421153/b7096e743e5951bdb1a4f268c9d9949a.html?affid=ac81902ea6025bafcfbdb8c515879b32
26,Robert Half,"Thu, 13 Dec 2018 02:44:26 GMT",Description Robert Half Technology's new REMOTE position for <b>Data</b> <b>Analyst</b> needs someone who provides comprehensive... - Bachelor's degree To apply to this <b>Data</b> <b>Analyst</b> position please email your resume separately to Technology doesn't change...,"Dallas, TX",$70000 - 75000 per year,USD,75000,70000,Y,,Data Analyst,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/cfe4cc5509c5a470521d248bd534db32.html?affid=ac81902ea6025bafcfbdb8c515879b32
27,North Texas LEAD,"Thu, 13 Dec 2018 00:48:22 GMT","The City of Fort Worth Water Reclamation Facility has an IT Business Systems <b>Data</b> <b>Analyst</b> job available to assist the..., debugging and analysis of system <b>data</b>. IT Business Systems <b>Data</b> <b>Analyst</b> job responsibilities include but are not limited...","Fort Worth, TX",,NaN,NaN,NaN,NaN,,IT Business Systems Data Analyst,http://jobviewtrack.com/en-us/job-1c19416479442d1b541d4e061b124e341c53000d04000a6a534c411d1c1a25365510010f0b14160027111a074f464e0d69051b0f07354e0204181d136762011b001d4f584e0d7e1d1c1a42195343290f0f0b1c53006a20270a69485e440a0a1d5454610d090d171411223d3c49205358494840174f2f49154c1a1b156f5554104758/35a13e7b1b191d3efc13b80b8f512156.html?affid=ac81902ea6025bafcfbdb8c515879b32
28,CVS Health,"Thu, 13 Dec 2018 00:15:48 GMT","Description : Job Description As the IT Systems Sr. <b>Analyst</b>, you will be responsible for application development... for the EDW team. The Sr.<b>Analyst</b> will be accountable for designing comprehensive solutions that meet business requirements...","Richardson, TX",,NaN,NaN,NaN,NaN,,Sr Analyst Data Warehouse,http://jobviewtrack.com/en-us/job-181841694c100e4e70155206000e1b1400003506081f5358492f7e164f2a46004143290f0f0b1c53006a2d125e4a1d6c430503175400222709150f473241060d011c5f58582f7e164f2f49154c1a1b156f5554144659/3b5656afe42d2602b51f15fe4e386719.html?affid=ac81902ea6025bafcfbdb8c515879b32
29,Chevron,"Wed, 12 Dec 2018 23:54:57 GMT","- Market <b>Data</b> <b>Analyst</b> located in Houston, TX Texas / United States through (December 17, 2018) at 11:59 p.m. (Eastern Standard... - Market <b>Data</b> <b>Analyst</b> position is a critical role supporting activities related to pricing <b>data</b> critical to ETRM application...","Houston, TX",,NaN,NaN,NaN,NaN,,S&T- Market Data Analyst,http://jobviewtrack.com/en-us/job-4f1e41694c100e4e661a410f11121a65284106030c070a6a534c411d1c1a2539411103041a47214100096b32444a51545e106d2a460041625a505f565c/8a6cd08d613a79ce6766c9961804136c.html?affid=ac81902ea6025bafcfbdb8c515879b32
...,...,...,...,...,...,...,...,...,...,...,...,...
50,Cenpatico,"Sat, 08 Dec 2018 08:14:59 GMT",Business <b>Analyst</b> II(Healthcare <b>Data</b>) USA-Texas-Austin Position Purpose: Perform various analysis and interpretation... to link business needs and objectives for assigned function Support business initiatives through <b>data</b> analysis...,"Austin, TX",,NaN,NaN,NaN,NaN,,Business Analyst II(Healthcare Data,http://jobviewtrack.com/en-us/job-1312416f5817060042075343290f0f0b1c53004821164b4749454e051d0b253c450204150604045211482d125e4a1d6c43050317540022211d12070900530748281d4b47445e5944262725365510010f0b1416003506081f5358490d69051b0f25365510010f0b1416003506081f5358492c1f54585615/bff6ad4c48679b97d7e0cd3da23bc717.html?affid=ac81902ea6025bafcfbdb8c515879b32

In [3]:
columns = ['company','date','title','locations','salary','url']
NewDf = pd.DataFrame(df,columns  = columns)
NewDf

,company,date,title,locations,salary,url
0,Alamo Drafthouse Cinemas,"Fri, 30 Nov 2018 08:10:25 GMT",Benefits Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-1d4f416f480a0a084e005343290f0f0b1c53006a281d4b47445e59662d0b4911460a1c126f5555174c5a/14b492f081cdb7f15be85ebe0ab90838.html?affid=ac81902ea6025bafcfbdb8c515879b32
1,Direct Energy,"Thu, 13 Dec 2018 08:22:24 GMT",Senior Data Systems Analyst,"Houston, TX",,http://jobviewtrack.com/en-us/job-4c18417e480a0601555464021c004e260b4118111a0728785843440b1d4e740d53170d0c1d47244e150410005e29794c59054f2f49154c1a1b156c341c53000d04000a6a534c411d1c1a2527450d010e1c47244e150410005e2a0f1c1c5556/84b6a31a6a269ca6f997f4e7def7228e.html?affid=ac81902ea6025bafcfbdb8c515879b32
2,The Hunt Corporation,"Thu, 13 Dec 2018 08:58:58 GMT",Project Controls Analyst II,"Austin, TX",$100000 per year,http://jobviewtrack.com/en-us/job-484d417d5f0b050b44000020070f1a150a4c0748281d4b47445e59663f1c481e45001c412d080b5406070500287b4f4247010c1a07354e0204181d1367611a09050a595f3f7d5f0b050b4400215158565655/1c4a5837439a3551788b39d7fc93d68e.html?affid=ac81902ea6025bafcfbdb8c515879b32
3,Ryder Logistics & Transportation,"Thu, 13 Dec 2018 08:52:22 GMT",Logistics Analyst,"Fort Worth, TX",,http://jobviewtrack.com/en-us/job-484a41614203061d531d4310482000060959071c6b32444a51545e106d22481349101c080d14641245585a43/c5f1a1895a4bd1b7cf718e890230b49b.html?affid=ac81902ea6025bafcfbdb8c515879b32
4,Maxim Government Services,"Thu, 06 Dec 2018 08:53:09 GMT",Board Certified Behavior Analyst BCBA,"Houston, TX",,http://jobviewtrack.com/en-us/job-1a12416f6e262e4e651b41110c412d0217541d0e00164e0b7f4845051907480600220600021e1654762a0612584f1d6e48161b07411d450748230b0f04561d071b536b455c4154171b6c651148021e08011545611a09050a595f1d6f6e262e6c64115217010707020100360d01125c42525f0d25010f4b0d53176a230b0f04561d071b536b455c4154171b6f1545115251/6652af1a4f32fd4e84a03f52abee1a44.html?affid=ac81902ea6025bafcfbdb8c515879b32
5,Paccar,"Wed, 12 Dec 2018 08:36:21 GMT",IT Data Analyst Intern - Summer 2019 Job,"Denton, TX",,http://jobviewtrack.com/en-us/job-1a4841694c100e4e661a410f11121a472c4e000d1b1d2878484040011d4e6e1a54061a0f4e2e3122271d041e4f591d6c430503175400002a06150b150b2230091d120a6a534c411d1c1a2527550e05041c472c4e000d1b1d2b190d141b5d/554317ca9a128720def2a168abe27089.html?affid=ac81902ea6025bafcfbdb8c515879b32
6,CPS Energy,"Wed, 12 Dec 2018 07:38:03 GMT",Data Engineer,"San Antonio, TX",,http://jobviewtrack.com/en-us/job-1b1341694c100e4e621a470a06040b1567651a0f001d4f4e4f2f69051b0f264611575e54/90892ae46aded8abcfe4233390fc136c.html?affid=ac81902ea6025bafcfbdb8c515879b32
7,NTT Data,"Thu, 13 Dec 2018 06:38:41 GMT",Clinical-Technical Help Desk Support Analyst,"Plano, TX",,http://jobviewtrack.com/en-us/job-1919416548081f4e6311530848350b040d4e1d0b081f0a78485d5d0b1d1a253c450f18412a02164b543b1c035a444f592f2c0a02575464061b0a4e260b4118111a07287f584e450a060d461800301d111e0817545429071246524e592f2c0a02575464061b0a4e3300431c0600104b473c1f1c57575e/57dd18864359cd933a9dd925d258b34b.html?affid=ac81902ea6025bafcfbdb8c515879b32
8,Bansar Technologies Inc,"Fri, 16 Nov 2018 08:14:29 GMT",Business Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-4f1f41694c100e4e661a410f11121a65244e150410005e297f585e0d010b540700220600021e1654542c08074b297f585e0d010b540722211d12070900530748281d4b47445e59655d5e104c12/975c852d5ee3c69118c9e27d142364b0.html?affid=ac81902ea6025bafcfbdb8c515879b32
9,Bansar Technologies Inc,"Sun, 11 Nov 2018 08:52:22 GMT",Data Architect/Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-4f4e41694c100e4e6606430b01150b04112230091d120a6a534c411d1c1a2535520000081a0206547629071246524e592f200e1a467512535f595c/5293c054e9b6ff312bf0e545b45c775f.html?affid=ac81902ea6025bafcfbdb8c515879b32
10,,"Sun, 04 Nov 2018 08:40:47 GMT",Financial Analyst Lead,"Austin, TX",,http://jobviewtrack.com/en-us/job-4918416148050b4e661a410f11121a6523491a090710434a512f61010e0a25354e0204181d1367661d06081d49425c410d25010f4b0d531769535e505d12/b4b9d6518853b7708d9883011f0ebc95.html?affid=ac81902ea6025bafcfbdb8c515879b32
11,Bansar Technologies Inc,"Mon, 05 Nov 2018 08:31:30 GMT",Senior Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-1d1f41694c100e4e661a410f11121a6536451a0106010a6f5c594c442e00461859101c633d020b491b1a49374b5f5c2f6c0a0e025e0754613b04000e0a52755a59441219/e731dd53e53b2f0dc8a73b7e14293dc4.html?affid=ac81902ea6025bafcfbdb8c515879b32
12,Targetbase,"Thu, 13 Dec 2018 08:21:38 GMT",Business Analyst,"Irving, TX",,http://jobviewtrack.com/en-us/job-4c1b416f5817060042075343290f0f0b1c53006a281d4b47445e59662d1b541d4e061b126f555411405b/45f8e6c4843306b045c1f32b254e3be2.html?affid=ac81902ea6025bafcfbdb8c515879b32
13,Targetbase,"Thu, 13 Dec 2018 08:20:15 GMT","Financial Analyst, Jr","Irving, TX",,http://jobviewtrack.com/en-us/job-4f1841675f44290749154e0001000247244e150410005e297b444305010d4e154c43290f0f0b1c53006a23010a6a534c411d1c1a25354e0204181d1367661d06081d49425c412c565e5f1347/7f29aa140df358c273aa268b81002186.html?affid=ac81902ea6025bafcfbdb8c515879b32
14,Targetbase,"Thu, 13 Dec 2018 08:13:42 GMT","Analyst, Analytics","Irving, TX",,http://jobviewtrack.com/en-us/job-121f416c43050317531d4310482000060959071c6b32444a51545e106d2f49154c1a1c080d14641245595d40/1c8a6c2a4e12081438b892eca6d956dd.html?affid=ac81902ea6025bafcfbdb8c515879b32
15,NTT Data,"Wed, 21 Nov 2018 08:06:44 GMT",Senior Business Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-491e417e480a0601555462161b08000216535429071246524e592f370a004e1b52432c001a0645611a09050a595f3f6f5817060042075343290f0f0b1c5300482d125e4a3f6f5817060042075343290f0f0b1c53006a2d125e4a1d6c430503175400215158565655/90544e861ae68a377b7a78f885b404f1.html?affid=ac81902ea6025bafcfbdb8c515879b32
16,NTT Data,"Wed, 21 Nov 2018 07:51:26 GMT",Senior Business Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-491e417e480a0601555462161b08000216535429071246524e592f370a004e1b52432c001a0645611a09050a595f3f6f5817060042075343290f0f0b1c5300482d125e4a3f6f5817060042075343290f0f0b1c53006a2d125e4a1d6c430503175400215158565655/60fbf3d7f6ed89b700b32b027bfbdb85.html?affid=ac81902ea6025bafcfbdb8c515879b32
17,CyberCoders,"Thu, 13 Dec 2018 08:42:26 GMT",Senior Data Analyst,"Austin, TX",$120000 - 160000 per year,http://jobviewtrack.com/en-us/job-1d13417e480a0601555464021c004e260b4118111a07286f5c594c442e00461859101c633d020b491b1a4932444a51545e106d3d421a490c1a412a0611417629071246524e592c565f591f46/1d42686ce46ee3fd51eb15c558cd6572.html?affid=ac81902ea6025bafcfbdb8c515879b32
18,Robert Half,"Thu, 13 Dec 2018 08:11:34 GMT",Financial Data Analyst,"Plano, TX",$18 - 19 per hour,http://jobviewtrack.com/en-us/job-4b4e416b440a0e00441d410f48250f1304003506081f5358492f6b0d010f4917490204412f09044c0d1b1d716e4a494c0d25010f4b0d53176a270709044e1701081f0a6f5c594c662e00461859101c605c56561844/01cc7b4c0267710c32cd3f6fbdc97eb7.html?affid=ac81902ea6025bafcfbdb8c515879b32
19,Robert Half,"Thu, 13 Dec 2018 08:10:08 GMT",Data Reporting Analyst,"Dallas, TX",,http://jobviewtrack.com/en-us/job-1f4941694c100e4e7511500c1a15070902003506081f5358492f69051b0f07354e0204181d136772111806015e42534a0d25010f4b0d53176a250f130400260d191c585f54434a662e00461859101c605c575c1543/13068bec6d53419ebe13104b4688fb95.html?affid=ac81902ea6025bafcfbdb8c515879b32
20,Wits Solutions Inc,"Thu, 13 Dec 2018 07:49:00 GMT",Data Scientist - Senior Analyst Consultant,"Irving, TX",,http://jobviewtrack.com/en-us/job-494a417e480a0601555464021c004e260b4118111a07286f5c594c442e00461859101c633d020b491b1a4932444a51545e106d3d421a490c1a413d040c451a1c00005e29794c59054f3d441d450d1c081d13641245595d40/d99deef90c5eee6a2dea1d3d79dc0b95.html?affid=ac81902ea6025bafcfbdb8c515879b32
21,ReqRoute,"Thu, 13 Dec 2018 06:52:35 GMT",9063 BI Data Analyst,"Plano, TX",,http://jobviewtrack.com/en-us/job-124a41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16471853/04589cac227c6607a365c5ed6cc37f3e.html?affid=ac81902ea6025bafcfbdb8c515879b32
22,St Joseph Health System,"Thu, 13 Dec 2018 06:20:01 GMT",Clinical Data Analyst,"Lubbock, TX",,http://jobviewtrack.com/en-us/job-4e4a416e410d010744154c432c001a0645611a09050a595f3f694c100e4e661a410f11121a65264c1d0600104b471d6c43050317540022200408000e064118482d125e4a3f6c430503175400215159535d52/37d54198098f1121c00e1b44fb011601.html?affid=ac81902ea6025bafcfbdb8c515879b32
23,Robert Half,"Thu, 13 Dec 2018 04:58:15 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/01907084254c2e9f47edc3eff67468ca.html?affid=ac81902ea6025bafcfbdb8c515879b32
24,Dow,"Thu, 13 Dec 2018 04:09:26 GMT",Production Data Analyst,"Texas City, TX",,http://jobviewtrack.com/en-us/job-491d41694c100e4e661a410f11121a6535521b0c1c105e4252430d25010f4b0d53176a2000060959071c6b23584459584e100601497664021c006f5554154051/70f7e5d64607db11f9e713a86c46b12c.html?affid=ac81902ea6025bafcfbdb8c515879b32
25,Atrilogy,"Thu, 13 Dec 2018 03:31:11 GMT",BI Data Analyst,"Westlake, TX",,http://jobviewtrack.com/en-us/job-1b1c41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16421153/b7096e743e5951bdb1a4f268c9d9949a.html?affid=ac81902ea6025bafcfbdb8c515879b32
26,Robert Half,"Thu, 13 Dec 2018 02:44:26 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/cfe4cc5509c5a470521d248bd534db32.html?affid=ac81902ea6025bafcfbdb8c515879b32
27,North Texas LEAD,"Thu, 13 Dec 2018 00:48:22 GMT",IT Business Systems Data Analyst,"Fort Worth, TX",,http://jobviewtrack.com/en-us/job-1c19416479442d1b541d4e061b124e341c53000d04000a6a534c411d1c1a25365510010f0b14160027111a074f464e0d69051b0f07354e0204181d136762011b001d4f584e0d7e1d1c1a42195343290f0f0b1c53006a20270a69485e440a0a1d5454610d090d171411223d3c49205358494840174f2f49154c1a1b156f5554104758/35a13e7b1b191d3efc13b80b8f512156.html?affid=ac81902ea6025bafcfbdb8c515879b32
28,CVS Health,"Thu, 13 Dec 2018 00:15:48 GMT",Sr Analyst Data Warehouse,"Richardson, TX",,http://jobviewtrack.com/en-us/job-181841694c100e4e70155206000e1b1400003506081f5358492f7e164f2a46004143290f0f0b1c53006a2d125e4a1d6c430503175400222709150f473241060d011c5f58582f7e164f2f49154c1a1b156f5554144659/3b5656afe42d2602b51f15fe4e386719.html?affid=ac81902ea6025bafcfbdb8c515879b32
29,Chevron,"Wed, 12 Dec 2018 23:54:57 GMT",S&T- Market Data Analyst,"Houston, TX",,http://jobviewtrack.com/en-us/job-4f1e41694c100e4e661a410f11121a65284106030c070a6a534c411d1c1a2539411103041a47214100096b32444a51545e106d2a460041625a505f565c/8a6cd08d613a79ce6766c9961804136c.html?affid=ac81902ea6025bafcfbdb8c515879b32
...,...,...,...,...,...,...
50,Cenpatico,"Sat, 08 Dec 2018 08:14:59 GMT",Business Analyst II(Healthcare Data,"Austin, TX",,http://jobviewtrack.com/en-us/job-1312416f5817060042075343290f0f0b1c53004821164b4749454e051d0b253c450204150604045211482d125e4a1d6c43050317540022211d12070900530748281d4b47445e5944262725365510010f0b1416003506081f5358490d69051b0f25365510010f0b1416003506081f5358492c1f54585615/bff6ad4c48679b97d7e0cd3da23bc717.html?affid=ac81902ea6025bafcfbdb8c515879b32
51,Cheniere,"Sat, 08 Dec 2018 07:17:38 GMT",Health and Safety Data Analyst,"Houston, TX",,http://jobviewtrack.com/en-us/job-1a4d41654805031a4f54410d0c413d06034500116b3b4f4a515945442b0f531500220600021e1654763b08154f5f440d4c0a0b4e631554026a250f1304003506081f5358492f65010e02531c002709150f665711455950/fe3e5e4701057eda33528c26757cdfdf.html?affid=ac81902ea6025bafcfbdb8c515879b32
52,,"Sat, 08 Dec 2018 01:25:54 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,http://jobviewtrack.com/en-us/job-181f417e42081a1a4e1b4e10482000060959071c6b205e595c594803060d0730411709633d0809550001061d59296e595f051b0b401d4343290f0f0b1c53006a3a07584a49484a0d0c4e741b4c161c080109162146585e4b18/cf91099fed241f07d51ec9dafed501aa.html?affid=ac81902ea6025bafcfbdb8c515879b32
53,Robert Half,"Sat, 08 Dec 2018 00:13:30 GMT",Data Analyst,"San Antonio, TX",$25 - 27 per hour,http://jobviewtrack.com/en-us/job-1b1a41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16401656/9d89c5b04bedd12ae4c24cc278ca7886.html?affid=ac81902ea6025bafcfbdb8c515879b32
54,Textron,"Sat, 08 Dec 2018 00:10:22 GMT",Data Analyst (V-247Program),"Fort Worth, TX",,http://jobviewtrack.com/en-us/job-1d1d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16441353/94a74f362462282297db8b3e9536d475.html?affid=ac81902ea6025bafcfbdb8c515879b32
55,Saxon Global,"Fri, 07 Dec 2018 23:52:58 GMT","Senior Data Analyst Developer (SSIS, SSRS)","San Antonio, TX",,http://jobviewtrack.com/en-us/job-1212417e480a0601555464021c004e260b4118111a0728786e647e443c3d752700270d170b0b0a50111a6b374b5f5c0d6c0a0e025e0754613b04000e0a525429071246524e592f373c27745473303a326f555414425d/e7895c514f0ab58aa35e9e3ac86369be.html?affid=ac81902ea6025bafcfbdb8c515879b32
56,Princeton Information,"Fri, 07 Dec 2018 23:51:06 GMT",Data Analyst - III,"Dallas, TX",$48.64 - 65.67 per hour,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/66b564baf28e500c88eb15f18b818229.html?affid=ac81902ea6025bafcfbdb8c515879b32
57,CornerStone Staffing,"Fri, 07 Dec 2018 23:45:31 GMT",Data Analyst,"Richardson, TX",$24 per hour,http://jobviewtrack.com/en-us/job-491941694c100e4e661a410f11121a65244e150410005e29794c59056e5c16401252/0a296d21088bc8c6f5b43b7fa590803a.html?affid=ac81902ea6025bafcfbdb8c515879b32
58,TechnipFMC,"Fri, 07 Dec 2018 23:03:43 GMT",Data Support Analyst,"Houston, TX",,http://jobviewtrack.com/en-us/job-1e4e41694c100e4e661a410f11121a653655041806015e0b7c434c08161d537664021c004e34105004071b07286a534c411d1c1a25275513180e1c1364124559584a/ff10336f6b5f898ba2bbc2ce5f61440c.html?affid=ac81902ea6025bafcfbdb8c515879b32
59,Advantage Resourcing,"Fri, 07 Dec 2018 08:53:33 GMT",Data Analyst,"Round Rock, TX",,http://jobviewtrack.com/en-us/job-1b1d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16401553/3d383317ec95a416bba3d964910a7349.html?affid=ac81902ea6025bafcfbdb8c515879b32
60,McKesson Technologies Limited,"Fri, 07 Dec 2018 08:50:32 GMT",Data Management Analyst,"Irving, TX",,http://jobviewtrack.com/en-us/job-191e41694c100e4e6a154e020f0403020b545429071246524e592f200e1a4654610d090d1714112230091d120a665c434c030a03421a5461250000060245190d07070a6a534c411d1c1a25354e0204181d13641245595d40/7fe62b912a8c652874633cc9ec74fb71.html?affid=ac81902ea6025bafcfbdb8c515879b32
61,Endurix,"Fri, 07 Dec 2018 08:49:51 GMT",HR Data Analyst,"Dallas, TX",,http://jobviewtrack.com/en-us/job-1b1941657f442b0f531500220600021e1654762c08074b0b7c434c08161d53766831482000060959071c6b3b780b757f2f2c3d4e6315540269535e5e5017/fd164df8f748f97ec4afdcfcfde01629.html?affid=ac81902ea6025bafcfbdb8c515879b32
62,,"Fri, 07 Dec 2018 08:37:49 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,http://jobviewtrack.com/en-us/job-184941694c100e4e661a410f11121a65364f181d1d1a45454e0d6c0a0e025e0754612c001a06457317010c1d494e3f7e59160e1a42134900482000060959071c6b205e595c594803060d07274f0f1d1507080b53755a59441219/e2bca52a3d745f599ceb460ac512a719.html?affid=ac81902ea6025bafcfbdb8c515879b32
63,EPMA,"Fri, 07 Dec 2018 08:27:22 GMT",Data Analyst,"Addison, TX",,http://jobviewtrack.com/en-us/job-181341694c100e4e661a410f11121a65244e150410005e29794c59056e5c1743145a/75ede1521a4ee84d61a78b58ff5a7f2d.html?affid=ac81902ea6025bafcfbdb8c515879b32
64,Verveba Analytics,"Fri, 07 Dec 2018 08:24:26 GMT",Data Analyst/ Hadoop developer,"Richardson, TX",,http://jobviewtrack.com/en-us/job-131a41694c100e4e661a410f11121a652d41100706030a6f585b4808001e420622220600021e1654542c0c054f47525d48166d2a460041432c041802094f040d1b716b455c4154171b6f1545145159/015f4650bba10c8394f017bb9809fcfb.html?affid=ac81902ea6025bafcfbdb8c515879b32
65,Statera,"Fri, 07 Dec 2018 07:50:25 GMT",Data Analyst - CTH - Dallas,"Dallas, TX",,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/34702c994b2cceca7b3a7f92437e2046.html?affid=ac81902ea6025bafcfbdb8c515879b32
66,,"Fri, 07 Dec 2018 06:29:55 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,http://jobviewtrack.com/en-us/job-124d417e42081a1a4e1b4e10482000060959071c6b32444a51545e106d3d530641170d0607044564151c087179445158590d0000547673171a001a0202491748281d4b47445e59655d5e104c12/8fd0ad47077b0885f31650dbcb2f7440.html?affid=ac81902ea6025bafcfbdb8c515879b32
67,,"Fri, 07 Dec 2018 04:57:12 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,http://jobviewtrack.com/en-us/job-124d417e42081a1a4e1b4e10482000060959071c6b32444a51545e106d3d530641170d0607044564151c087179445158590d0000547673171a001a0202491748281d4b47445e59655d5e104c12/926e6ef1cb221909334d8f7009a43893.html?affid=ac81902ea6025bafcfbdb8c515879b32
68,Texas A&M University,"Fri, 07 Dec 2018 04:41:44 GMT",Data Analyst,"College Station, TX",,http://jobviewtrack.com/en-us/job-1c1f41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1154/aa9e1faa1902dcdeac1e78b849b1ef5a.html?affid=ac81902ea6025bafcfbdb8c515879b32
69,Spectrum,"Thu, 06 Dec 2018 23:06:27 GMT",Bus Data Analyst-Call Analytic,"Austin, TX",,http://jobviewtrack.com/en-us/job-191b41694c100e4e661a410f11121a65275507482b065929794c59054f2f49154c1a1c080d65244e150410005e29794c59056e5c17431851/f509658f5538aa61073a0008db463231.html?affid=ac81902ea6025bafcfbdb8c515879b32
70,USAA,"Thu, 06 Dec 2018 08:58:51 GMT",Data Quality Analyst I,"San Antonio, TX",,http://jobviewtrack.com/en-us/job-124941694c100e4e7601410f01151747244e150410005e29794c59054f2f49154c1a1b156c36104118011d0a0a6a534c411d1c1a2530411709413f12044c1d1c10716b455c4154171b6f154514555d/9815c57f34e7624cb0373019ff5b308d.html?affid=ac81902ea6025bafcfbdb8c515879b32
71,,"Thu, 06 Dec 2018 08:55:31 GMT",TAR-Data Analyst,"Fort Worth, TX",,http://jobviewtrack.com/en-us/job-1d1d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16441353/bb4ab960510cdd063f9ea0e2320b9374.html?affid=ac81902ea6025bafcfbdb8c515879b32
72,,"Thu, 06 Dec 2018 08:49:01 GMT",Data Services Analyst,"Dallas, TX",,http://jobviewtrack.com/en-us/job-1a4f41694c100e4e661a410f11121a652141000949204f594b444e011c6c7411521501020b1445611a09050a595f3f6c430503175400222709150f6657104d5d5e/6c1db282a97c7997a26b4252d79cc003.html?affid=ac81902ea6025bafcfbdb8c515879b32
73,,"Thu, 06 Dec 2018 08:43:05 GMT",Data Analyst,"Frisco, TX",,http://jobviewtrack.com/en-us/job-1e1b41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16441355/d0f0091fffdc0d3907c3221e85aca54a.html?affid=ac81902ea6025bafcfbdb8c515879b32
74,Bank of America,"Thu, 06 Dec 2018 06:42:29 GMT",Data Analyst,"Plano, TX",,http://jobviewtrack.com/en-us/job-124a41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16471853/c3cdbba9ac3e1ac26d175ed874430eae.html?affid=ac81902ea6025bafcfbdb8c515879b32
75,,"Thu, 06 Dec 2018 01:44:20 GMT",Data / Systems Business Analyst II,"Irving, TX",,http://jobviewtrack.com/en-us/job-491341694c100e4e661a410f11121a6527550701071659581d7e54171b0b4a0722211d120709005307483a0a595f58405e442e00461859101c632f09044c0d1b1d71685e4e4443011c1d07354e0204181d134564151c0872181a0c191e/7e151125afb3dd2662af02f556601bc3.html?affid=ac81902ea6025bafcfbdb8c515879b32
76,DSI Systems,"Wed, 05 Dec 2018 23:56:33 GMT",Data Analyst,"Richardson, TX",,http://jobviewtrack.com/en-us/job-491941694c100e4e661a410f11121a65244e150410005e29794c59056e5c16401252/834de28146cf7bfd5cd8ba379c9dc48e.html?affid=ac81902ea6025bafcfbdb8c515879b32
77,IT Trailblazers LLC,"Wed, 05 Dec 2018 23:08:05 GMT",Senior Business Analyst Business Analyst (Data Transformation),"Plano, TX",,http://jobviewtrack.com/en-us/job-481d417e480a0601555462161b08000216535429071246524e592f370a004e1b52432c001a0645611a09050a595f3f6f5817060042075343290f0f0b1c5300482d125e4a3f6f5817060042075343290f0f0b1c53006a2d125e4a1d6c430503175400215159525657/aeb572b85a2dc5960fd67391479daf92.html?affid=ac81902ea6025bafcfbdb8c515879b32

In [4]:
import requests
import json
import re
import urllib
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as BS

actual_link=[]

for index, row in NewDf.iterrows():
    htmlfile = urllib.urlopen(row['url'])
#Query intermediary URL for actual job site URL 
    url=urllib.urlopen(row['url'])
    soup=BS(url,'html.parser')
    m_link=soup.find("meta")
    new_link=m_link['content'][7:]
    print new_link
    actual_link.append(new_link)

NewDf['actual_link']=actual_link
NewDf

https://www.careerjet.com/job/14b492f081cdb7f15be85ebe0ab90838.html
https://www.careerjet.com/job/84b6a31a6a269ca6f997f4e7def7228e.html
https://www.careerjet.com/job/1c4a5837439a3551788b39d7fc93d68e.html
https://www.careerjet.com/job/c5f1a1895a4bd1b7cf718e890230b49b.html
https://www.careerjet.com/job/6652af1a4f32fd4e84a03f52abee1a44.html
https://www.careerjet.com/job/554317ca9a128720def2a168abe27089.html
https://www.careerjet.com/job/90892ae46aded8abcfe4233390fc136c.html
https://www.careerjet.com/job/57dd18864359cd933a9dd925d258b34b.html
https://www.careerjet.com/job/975c852d5ee3c69118c9e27d142364b0.html
https://www.careerjet.com/job/5293c054e9b6ff312bf0e545b45c775f.html
https://www.careerjet.com/job/b4b9d6518853b7708d9883011f0ebc95.html
https://www.careerjet.com/job/e731dd53e53b2f0dc8a73b7e14293dc4.html
https://www.careerjet.com/job/45f8e6c4843306b045c1f32b254e3be2.html
https://www.careerjet.com/job/7f29aa140df358c273aa268b81002186.html
https://www.careerjet.com/job/1c8a6c2a4e12081438b892eca6d956dd.html
https://www.careerjet.com/job/90544e861ae68a377b7a78f885b404f1.html
https://www.careerjet.com/job/60fbf3d7f6ed89b700b32b027bfbdb85.html
https://www.careerjet.com/job/1d42686ce46ee3fd51eb15c558cd6572.html
https://www.careerjet.com/job/01cc7b4c0267710c32cd3f6fbdc97eb7.html
https://www.careerjet.com/job/13068bec6d53419ebe13104b4688fb95.html
https://www.careerjet.com/job/d99deef90c5eee6a2dea1d3d79dc0b95.html
https://www.careerjet.com/job/04589cac227c6607a365c5ed6cc37f3e.html
https://www.careerjet.com/job/37d54198098f1121c00e1b44fb011601.html
https://www.careerjet.com/job/01907084254c2e9f47edc3eff67468ca.html
https://www.careerjet.com/job/70f7e5d64607db11f9e713a86c46b12c.html
https://www.careerjet.com/job/b7096e743e5951bdb1a4f268c9d9949a.html
https://www.careerjet.com/job/cfe4cc5509c5a470521d248bd534db32.html
https://www.careerjet.com/job/35a13e7b1b191d3efc13b80b8f512156.html
https://www.careerjet.com/job/3b5656afe42d2602b51f15fe4e386719.html
https://www.careerjet.com/job/8a6cd08d613a79ce6766c9961804136c.html
https://www.careerjet.com/job/4200d3c2cbf85ef7fb112861a9cec95c.html
https://www.careerjet.com/job/86637a5cd91a9e99554988d89c39d111.html
https://www.careerjet.com/job/28eaed0266f1b6e5510e1d2ba37bca0e.html
https://www.careerjet.com/job/bbc99d9410cdc7d083ca2ff3d71371fa.html
https://www.careerjet.com/job/793b2feb7d6518db7d35cfcfd79ef81c.html
https://www.careerjet.com/job/c5073c71dcd6dce89d7f71e1c2a34bec.html
https://www.careerjet.com/job/8e214533640835ca9713bb49e387b05c.html
https://www.careerjet.com/job/822717fd8d6e7d936adb14f12abffee1.html
https://www.careerjet.com/job/077922c1f0dba500b1aec753e1f139bd.html
https://www.careerjet.com/job/3b946971936f71563e0ca5f6da7948ba.html
https://www.careerjet.com/job/7c7e60ebaed945b68148602921dab207.html
https://www.careerjet.com/job/1c95391cfaf69d7fe53fa331d7c4fc95.html
https://www.careerjet.com/job/4fcd45aed9fe4805f6c7607543ca99c5.html
https://www.careerjet.com/job/b0d75e410fcdd45fa28b207c8e94426d.html
https://www.careerjet.com/job/9a04cb3264a381c8871fb69422f37b3a.html
https://www.careerjet.com/job/d0a4aa88494d2aa2a4ef438cc7139be3.html
https://www.careerjet.com/job/31f05ffbe9a5f7dff6cd66adcdc215ea.html
https://www.careerjet.com/job/d5a622ff13af2b6683051263364f1ecf.html
https://www.careerjet.com/job/61368c8e9f295e50d3bb57bf42b7be26.html
https://www.careerjet.com/job/8f09300055d9d599f6f066e3a7066ccc.html
https://www.careerjet.com/job/bff6ad4c48679b97d7e0cd3da23bc717.html
https://www.careerjet.com/job/fe3e5e4701057eda33528c26757cdfdf.html
https://www.careerjet.com/job/cf91099fed241f07d51ec9dafed501aa.html
https://www.careerjet.com/job/9d89c5b04bedd12ae4c24cc278ca7886.html
https://www.careerjet.com/job/94a74f362462282297db8b3e9536d475.html
https://www.careerjet.com/job/e7895c514f0ab58aa35e9e3ac86369be.html
https://www.careerjet.com/job/66b564baf28e500c88eb15f18b818229.html
https://www.careerjet.com/job/0a296d21088bc8c6f5b43b7fa590803a.html
https://www.careerjet.com/job/ff10336f6b5f898ba2bbc2ce5f61440c.html
https://www.careerjet.com/job/3d383317ec95a416bba3d964910a7349.html
https://www.careerjet.com/job/7fe62b912a8c652874633cc9ec74fb71.html
https://www.careerjet.com/job/fd164df8f748f97ec4afdcfcfde01629.html
https://www.careerjet.com/job/e2bca52a3d745f599ceb460ac512a719.html
https://www.careerjet.com/job/75ede1521a4ee84d61a78b58ff5a7f2d.html
https://www.careerjet.com/job/015f4650bba10c8394f017bb9809fcfb.html
https://www.careerjet.com/job/34702c994b2cceca7b3a7f92437e2046.html
https://www.careerjet.com/job/8fd0ad47077b0885f31650dbcb2f7440.html
https://www.careerjet.com/job/926e6ef1cb221909334d8f7009a43893.html
https://www.careerjet.com/job/aa9e1faa1902dcdeac1e78b849b1ef5a.html
https://www.careerjet.com/job/f509658f5538aa61073a0008db463231.html
https://www.careerjet.com/job/9815c57f34e7624cb0373019ff5b308d.html
https://www.careerjet.com/job/bb4ab960510cdd063f9ea0e2320b9374.html
https://www.careerjet.com/job/6c1db282a97c7997a26b4252d79cc003.html
https://www.careerjet.com/job/d0f0091fffdc0d3907c3221e85aca54a.html
https://www.careerjet.com/job/c3cdbba9ac3e1ac26d175ed874430eae.html
https://www.careerjet.com/job/7e151125afb3dd2662af02f556601bc3.html
https://www.careerjet.com/job/834de28146cf7bfd5cd8ba379c9dc48e.html
https://www.careerjet.com/job/aeb572b85a2dc5960fd67391479daf92.html
https://www.careerjet.com/job/66319dcf17f7a611701ee1c8b6fa505e.html
https://www.careerjet.com/job/13b24cd13e18ee6d89bfb7cf76e92aa2.html

,company,date,title,locations,salary,url,actual_link
0,Alamo Drafthouse Cinemas,"Fri, 30 Nov 2018 08:10:25 GMT",Benefits Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-1d4f416f480a0a084e005343290f0f0b1c53006a281d4b47445e59662d0b4911460a1c126f5555174c5a/14b492f081cdb7f15be85ebe0ab90838.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/14b492f081cdb7f15be85ebe0ab90838.html
1,Direct Energy,"Thu, 13 Dec 2018 08:22:24 GMT",Senior Data Systems Analyst,"Houston, TX",,http://jobviewtrack.com/en-us/job-4c18417e480a0601555464021c004e260b4118111a0728785843440b1d4e740d53170d0c1d47244e150410005e29794c59054f2f49154c1a1b156c341c53000d04000a6a534c411d1c1a2527450d010e1c47244e150410005e2a0f1c1c5556/84b6a31a6a269ca6f997f4e7def7228e.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/84b6a31a6a269ca6f997f4e7def7228e.html
2,The Hunt Corporation,"Thu, 13 Dec 2018 08:58:58 GMT",Project Controls Analyst II,"Austin, TX",$100000 per year,http://jobviewtrack.com/en-us/job-484d417d5f0b050b44000020070f1a150a4c0748281d4b47445e59663f1c481e45001c412d080b5406070500287b4f4247010c1a07354e0204181d1367611a09050a595f3f7d5f0b050b4400215158565655/1c4a5837439a3551788b39d7fc93d68e.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/1c4a5837439a3551788b39d7fc93d68e.html
3,Ryder Logistics & Transportation,"Thu, 13 Dec 2018 08:52:22 GMT",Logistics Analyst,"Fort Worth, TX",,http://jobviewtrack.com/en-us/job-484a41614203061d531d4310482000060959071c6b32444a51545e106d22481349101c080d14641245585a43/c5f1a1895a4bd1b7cf718e890230b49b.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/c5f1a1895a4bd1b7cf718e890230b49b.html
4,Maxim Government Services,"Thu, 06 Dec 2018 08:53:09 GMT",Board Certified Behavior Analyst BCBA,"Houston, TX",,http://jobviewtrack.com/en-us/job-1a12416f6e262e4e651b41110c412d0217541d0e00164e0b7f4845051907480600220600021e1654762a0612584f1d6e48161b07411d450748230b0f04561d071b536b455c4154171b6c651148021e08011545611a09050a595f1d6f6e262e6c64115217010707020100360d01125c42525f0d25010f4b0d53176a230b0f04561d071b536b455c4154171b6f1545115251/6652af1a4f32fd4e84a03f52abee1a44.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/6652af1a4f32fd4e84a03f52abee1a44.html
5,Paccar,"Wed, 12 Dec 2018 08:36:21 GMT",IT Data Analyst Intern - Summer 2019 Job,"Denton, TX",,http://jobviewtrack.com/en-us/job-1a4841694c100e4e661a410f11121a472c4e000d1b1d2878484040011d4e6e1a54061a0f4e2e3122271d041e4f591d6c430503175400002a06150b150b2230091d120a6a534c411d1c1a2527550e05041c472c4e000d1b1d2b190d141b5d/554317ca9a128720def2a168abe27089.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/554317ca9a128720def2a168abe27089.html
6,CPS Energy,"Wed, 12 Dec 2018 07:38:03 GMT",Data Engineer,"San Antonio, TX",,http://jobviewtrack.com/en-us/job-1b1341694c100e4e621a470a06040b1567651a0f001d4f4e4f2f69051b0f264611575e54/90892ae46aded8abcfe4233390fc136c.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/90892ae46aded8abcfe4233390fc136c.html
7,NTT Data,"Thu, 13 Dec 2018 06:38:41 GMT",Clinical-Technical Help Desk Support Analyst,"Plano, TX",,http://jobviewtrack.com/en-us/job-1919416548081f4e6311530848350b040d4e1d0b081f0a78485d5d0b1d1a253c450f18412a02164b543b1c035a444f592f2c0a02575464061b0a4e260b4118111a07287f584e450a060d461800301d111e0817545429071246524e592f2c0a02575464061b0a4e3300431c0600104b473c1f1c57575e/57dd18864359cd933a9dd925d258b34b.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/57dd18864359cd933a9dd925d258b34b.html
8,Bansar Technologies Inc,"Fri, 16 Nov 2018 08:14:29 GMT",Business Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-4f1f41694c100e4e661a410f11121a65244e150410005e297f585e0d010b540700220600021e1654542c08074b297f585e0d010b540722211d12070900530748281d4b47445e59655d5e104c12/975c852d5ee3c69118c9e27d142364b0.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/975c852d5ee3c69118c9e27d142364b0.html
9,Bansar Technologies Inc,"Sun, 11 Nov 2018 08:52:22 GMT",Data Architect/Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-4f4e41694c100e4e6606430b01150b04112230091d120a6a534c411d1c1a2535520000081a0206547629071246524e592f200e1a467512535f595c/5293c054e9b6ff312bf0e545b45c775f.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/5293c054e9b6ff312bf0e545b45c775f.html
10,,"Sun, 04 Nov 2018 08:40:47 GMT",Financial Analyst Lead,"Austin, TX",,http://jobviewtrack.com/en-us/job-4918416148050b4e661a410f11121a6523491a090710434a512f61010e0a25354e0204181d1367661d06081d49425c410d25010f4b0d531769535e505d12/b4b9d6518853b7708d9883011f0ebc95.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/b4b9d6518853b7708d9883011f0ebc95.html
11,Bansar Technologies Inc,"Mon, 05 Nov 2018 08:31:30 GMT",Senior Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-1d1f41694c100e4e661a410f11121a6536451a0106010a6f5c594c442e00461859101c633d020b491b1a49374b5f5c2f6c0a0e025e0754613b04000e0a52755a59441219/e731dd53e53b2f0dc8a73b7e14293dc4.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/e731dd53e53b2f0dc8a73b7e14293dc4.html
12,Targetbase,"Thu, 13 Dec 2018 08:21:38 GMT",Business Analyst,"Irving, TX",,http://jobviewtrack.com/en-us/job-4c1b416f5817060042075343290f0f0b1c53006a281d4b47445e59662d1b541d4e061b126f555411405b/45f8e6c4843306b045c1f32b254e3be2.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/45f8e6c4843306b045c1f32b254e3be2.html
13,Targetbase,"Thu, 13 Dec 2018 08:20:15 GMT","Financial Analyst, Jr","Irving, TX",,http://jobviewtrack.com/en-us/job-4f1841675f44290749154e0001000247244e150410005e297b444305010d4e154c43290f0f0b1c53006a23010a6a534c411d1c1a25354e0204181d1367661d06081d49425c412c565e5f1347/7f29aa140df358c273aa268b81002186.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/7f29aa140df358c273aa268b81002186.html
14,Targetbase,"Thu, 13 Dec 2018 08:13:42 GMT","Analyst, Analytics","Irving, TX",,http://jobviewtrack.com/en-us/job-121f416c43050317531d4310482000060959071c6b32444a51545e106d2f49154c1a1c080d14641245595d40/1c8a6c2a4e12081438b892eca6d956dd.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/1c8a6c2a4e12081438b892eca6d956dd.html
15,NTT Data,"Wed, 21 Nov 2018 08:06:44 GMT",Senior Business Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-491e417e480a0601555462161b08000216535429071246524e592f370a004e1b52432c001a0645611a09050a595f3f6f5817060042075343290f0f0b1c5300482d125e4a3f6f5817060042075343290f0f0b1c53006a2d125e4a1d6c430503175400215158565655/90544e861ae68a377b7a78f885b404f1.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/90544e861ae68a377b7a78f885b404f1.html
16,NTT Data,"Wed, 21 Nov 2018 07:51:26 GMT",Senior Business Data Analyst,"Austin, TX",,http://jobviewtrack.com/en-us/job-491e417e480a0601555462161b08000216535429071246524e592f370a004e1b52432c001a0645611a09050a595f3f6f5817060042075343290f0f0b1c5300482d125e4a3f6f5817060042075343290f0f0b1c53006a2d125e4a1d6c430503175400215158565655/60fbf3d7f6ed89b700b32b027bfbdb85.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/60fbf3d7f6ed89b700b32b027bfbdb85.html
17,CyberCoders,"Thu, 13 Dec 2018 08:42:26 GMT",Senior Data Analyst,"Austin, TX",$120000 - 160000 per year,http://jobviewtrack.com/en-us/job-1d13417e480a0601555464021c004e260b4118111a07286f5c594c442e00461859101c633d020b491b1a4932444a51545e106d3d421a490c1a412a0611417629071246524e592c565f591f46/1d42686ce46ee3fd51eb15c558cd6572.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/1d42686ce46ee3fd51eb15c558cd6572.html
18,Robert Half,"Thu, 13 Dec 2018 08:11:34 GMT",Financial Data Analyst,"Plano, TX",$18 - 19 per hour,http://jobviewtrack.com/en-us/job-4b4e416b440a0e00441d410f48250f1304003506081f5358492f6b0d010f4917490204412f09044c0d1b1d716e4a494c0d25010f4b0d53176a270709044e1701081f0a6f5c594c662e00461859101c605c56561844/01cc7b4c0267710c32cd3f6fbdc97eb7.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/01cc7b4c0267710c32cd3f6fbdc97eb7.html
19,Robert Half,"Thu, 13 Dec 2018 08:10:08 GMT",Data Reporting Analyst,"Dallas, TX",,http://jobviewtrack.com/en-us/job-1f4941694c100e4e7511500c1a15070902003506081f5358492f69051b0f07354e0204181d136772111806015e42534a0d25010f4b0d53176a250f130400260d191c585f54434a662e00461859101c605c575c1543/13068bec6d53419ebe13104b4688fb95.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/13068bec6d53419ebe13104b4688fb95.html
20,Wits Solutions Inc,"Thu, 13 Dec 2018 07:49:00 GMT",Data Scientist - Senior Analyst Consultant,"Irving, TX",,http://jobviewtrack.com/en-us/job-494a417e480a0601555464021c004e260b4118111a07286f5c594c442e00461859101c633d020b491b1a4932444a51545e106d3d421a490c1a413d040c451a1c00005e29794c59054f3d441d450d1c081d13641245595d40/d99deef90c5eee6a2dea1d3d79dc0b95.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/d99deef90c5eee6a2dea1d3d79dc0b95.html
21,ReqRoute,"Thu, 13 Dec 2018 06:52:35 GMT",9063 BI Data Analyst,"Plano, TX",,http://jobviewtrack.com/en-us/job-124a41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16471853/04589cac227c6607a365c5ed6cc37f3e.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/04589cac227c6607a365c5ed6cc37f3e.html
22,St Joseph Health System,"Thu, 13 Dec 2018 06:20:01 GMT",Clinical Data Analyst,"Lubbock, TX",,http://jobviewtrack.com/en-us/job-4e4a416e410d010744154c432c001a0645611a09050a595f3f694c100e4e661a410f11121a65264c1d0600104b471d6c43050317540022200408000e064118482d125e4a3f6c430503175400215159535d52/37d54198098f1121c00e1b44fb011601.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/37d54198098f1121c00e1b44fb011601.html
23,Robert Half,"Thu, 13 Dec 2018 04:58:15 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/01907084254c2e9f47edc3eff67468ca.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/01907084254c2e9f47edc3eff67468ca.html
24,Dow,"Thu, 13 Dec 2018 04:09:26 GMT",Production Data Analyst,"Texas City, TX",,http://jobviewtrack.com/en-us/job-491d41694c100e4e661a410f11121a6535521b0c1c105e4252430d25010f4b0d53176a2000060959071c6b23584459584e100601497664021c006f5554154051/70f7e5d64607db11f9e713a86c46b12c.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/70f7e5d64607db11f9e713a86c46b12c.html
25,Atrilogy,"Thu, 13 Dec 2018 03:31:11 GMT",BI Data Analyst,"Westlake, TX",,http://jobviewtrack.com/en-us/job-1b1c41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16421153/b7096e743e5951bdb1a4f268c9d9949a.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/b7096e743e5951bdb1a4f268c9d9949a.html
26,Robert Half,"Thu, 13 Dec 2018 02:44:26 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/cfe4cc5509c5a470521d248bd534db32.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/cfe4cc5509c5a470521d248bd534db32.html
27,North Texas LEAD,"Thu, 13 Dec 2018 00:48:22 GMT",IT Business Systems Data Analyst,"Fort Worth, TX",,http://jobviewtrack.com/en-us/job-1c19416479442d1b541d4e061b124e341c53000d04000a6a534c411d1c1a25365510010f0b14160027111a074f464e0d69051b0f07354e0204181d136762011b001d4f584e0d7e1d1c1a42195343290f0f0b1c53006a20270a69485e440a0a1d5454610d090d171411223d3c49205358494840174f2f49154c1a1b156f5554104758/35a13e7b1b191d3efc13b80b8f512156.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/35a13e7b1b191d3efc13b80b8f512156.html
28,CVS Health,"Thu, 13 Dec 2018 00:15:48 GMT",Sr Analyst Data Warehouse,"Richardson, TX",,http://jobviewtrack.com/en-us/job-181841694c100e4e70155206000e1b1400003506081f5358492f7e164f2a46004143290f0f0b1c53006a2d125e4a1d6c430503175400222709150f473241060d011c5f58582f7e164f2f49154c1a1b156f5554144659/3b5656afe42d2602b51f15fe4e386719.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/3b5656afe42d2602b51f15fe4e386719.html
29,Chevron,"Wed, 12 Dec 2018 23:54:57 GMT",S&T- Market Data Analyst,"Houston, TX",,http://jobviewtrack.com/en-us/job-4f1e41694c100e4e661a410f11121a65284106030c070a6a534c411d1c1a2539411103041a47214100096b32444a51545e106d2a460041625a505f565c/8a6cd08d613a79ce6766c9961804136c.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/8a6cd08d613a79ce6766c9961804136c.html
...,...,...,...,...,...,...,...
50,Cenpatico,"Sat, 08 Dec 2018 08:14:59 GMT",Business Analyst II(Healthcare Data,"Austin, TX",,http://jobviewtrack.com/en-us/job-1312416f5817060042075343290f0f0b1c53004821164b4749454e051d0b253c450204150604045211482d125e4a1d6c43050317540022211d12070900530748281d4b47445e5944262725365510010f0b1416003506081f5358490d69051b0f25365510010f0b1416003506081f5358492c1f54585615/bff6ad4c48679b97d7e0cd3da23bc717.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/bff6ad4c48679b97d7e0cd3da23bc717.html
51,Cheniere,"Sat, 08 Dec 2018 07:17:38 GMT",Health and Safety Data Analyst,"Houston, TX",,http://jobviewtrack.com/en-us/job-1a4d41654805031a4f54410d0c413d06034500116b3b4f4a515945442b0f531500220600021e1654763b08154f5f440d4c0a0b4e631554026a250f1304003506081f5358492f65010e02531c002709150f665711455950/fe3e5e4701057eda33528c26757cdfdf.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/fe3e5e4701057eda33528c26757cdfdf.html
52,,"Sat, 08 Dec 2018 01:25:54 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,http://jobviewtrack.com/en-us/job-181f417e42081a1a4e1b4e10482000060959071c6b205e595c594803060d0730411709633d0809550001061d59296e595f051b0b401d4343290f0f0b1c53006a3a07584a49484a0d0c4e741b4c161c080109162146585e4b18/cf91099fed241f07d51ec9dafed501aa.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/cf91099fed241f07d51ec9dafed501aa.html
53,Robert Half,"Sat, 08 Dec 2018 00:13:30 GMT",Data Analyst,"San Antonio, TX",$25 - 27 per hour,http://jobviewtrack.com/en-us/job-1b1a41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16401656/9d89c5b04bedd12ae4c24cc278ca7886.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/9d89c5b04bedd12ae4c24cc278ca7886.html
54,Textron,"Sat, 08 Dec 2018 00:10:22 GMT",Data Analyst (V-247Program),"Fort Worth, TX",,http://jobviewtrack.com/en-us/job-1d1d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16441353/94a74f362462282297db8b3e9536d475.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/94a74f362462282297db8b3e9536d475.html
55,Saxon Global,"Fri, 07 Dec 2018 23:52:58 GMT","Senior Data Analyst Developer (SSIS, SSRS)","San Antonio, TX",,http://jobviewtrack.com/en-us/job-1212417e480a0601555464021c004e260b4118111a0728786e647e443c3d752700270d170b0b0a50111a6b374b5f5c0d6c0a0e025e0754613b04000e0a525429071246524e592f373c27745473303a326f555414425d/e7895c514f0ab58aa35e9e3ac86369be.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/e7895c514f0ab58aa35e9e3ac86369be.html
56,Princeton Information,"Fri, 07 Dec 2018 23:51:06 GMT",Data Analyst - III,"Dallas, TX",$48.64 - 65.67 per hour,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/66b564baf28e500c88eb15f18b818229.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/66b564baf28e500c88eb15f18b818229.html
57,CornerStone Staffing,"Fri, 07 Dec 2018 23:45:31 GMT",Data Analyst,"Richardson, TX",$24 per hour,http://jobviewtrack.com/en-us/job-491941694c100e4e661a410f11121a65244e150410005e29794c59056e5c16401252/0a296d21088bc8c6f5b43b7fa590803a.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/0a296d21088bc8c6f5b43b7fa590803a.html
58,TechnipFMC,"Fri, 07 Dec 2018 23:03:43 GMT",Data Support Analyst,"Houston, TX",,http://jobviewtrack.com/en-us/job-1e4e41694c100e4e661a410f11121a653655041806015e0b7c434c08161d537664021c004e34105004071b07286a534c411d1c1a25275513180e1c1364124559584a/ff10336f6b5f898ba2bbc2ce5f61440c.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/ff10336f6b5f898ba2bbc2ce5f61440c.html
59,Advantage Resourcing,"Fri, 07 Dec 2018 08:53:33 GMT",Data Analyst,"Round Rock, TX",,http://jobviewtrack.com/en-us/job-1b1d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c16401553/3d383317ec95a416bba3d964910a7349.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/3d383317ec95a416bba3d964910a7349.html
60,McKesson Technologies Limited,"Fri, 07 Dec 2018 08:50:32 GMT",Data Management Analyst,"Irving, TX",,http://jobviewtrack.com/en-us/job-191e41694c100e4e6a154e020f0403020b545429071246524e592f200e1a4654610d090d1714112230091d120a665c434c030a03421a5461250000060245190d07070a6a534c411d1c1a25354e0204181d13641245595d40/7fe62b912a8c652874633cc9ec74fb71.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/7fe62b912a8c652874633cc9ec74fb71.html
61,Endurix,"Fri, 07 Dec 2018 08:49:51 GMT",HR Data Analyst,"Dallas, TX",,http://jobviewtrack.com/en-us/job-1b1941657f442b0f531500220600021e1654762c08074b0b7c434c08161d53766831482000060959071c6b3b780b757f2f2c3d4e6315540269535e5e5017/fd164df8f748f97ec4afdcfcfde01629.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/fd164df8f748f97ec4afdcfcfde01629.html
62,,"Fri, 07 Dec 2018 08:37:49 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,http://jobviewtrack.com/en-us/job-184941694c100e4e661a410f11121a65364f181d1d1a45454e0d6c0a0e025e0754612c001a06457317010c1d494e3f7e59160e1a42134900482000060959071c6b205e595c594803060d07274f0f1d1507080b53755a59441219/e2bca52a3d745f599ceb460ac512a719.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/e2bca52a3d745f599ceb460ac512a719.html
63,EPMA,"Fri, 07 Dec 2018 08:27:22 GMT",Data Analyst,"Addison, TX",,http://jobviewtrack.com/en-us/job-181341694c100e4e661a410f11121a65244e150410005e29794c59056e5c1743145a/75ede1521a4ee84d61a78b58ff5a7f2d.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/75ede1521a4ee84d61a78b58ff5a7f2d.html
64,Verveba Analytics,"Fri, 07 Dec 2018 08:24:26 GMT",Data Analyst/ Hadoop developer,"Richardson, TX",,http://jobviewtrack.com/en-us/job-131a41694c100e4e661a410f11121a652d41100706030a6f585b4808001e420622220600021e1654542c0c054f47525d48166d2a460041432c041802094f040d1b716b455c4154171b6f1545145159/015f4650bba10c8394f017bb9809fcfb.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/015f4650bba10c8394f017bb9809fcfb.html
65,Statera,"Fri, 07 Dec 2018 07:50:25 GMT",Data Analyst - CTH - Dallas,"Dallas, TX",,http://jobviewtrack.com/en-us/job-1b4d41694c100e4e661a410f11121a65244e150410005e29794c59056e5c174d1554/34702c994b2cceca7b3a7f92437e2046.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/34702c994b2cceca7b3a7f92437e2046.html
66,,"Fri, 07 Dec 2018 06:29:55 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,http://jobviewtrack.com/en-us/job-124d417e42081a1a4e1b4e10482000060959071c6b32444a51545e106d3d530641170d0607044564151c087179445158590d0000547673171a001a0202491748281d4b47445e59655d5e104c12/8fd0ad47077b0885f31650dbcb2f7440.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/8fd0ad47077b0885f31650dbcb2f7440.html
67,,"Fri, 07 Dec 2018 04:57:12 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,http://jobviewtrack.com/en-us/job-124d417e42081a1a4e1b4e10482000060959071c6b32444a51545e106d3d530641170d0607044564151c087179445158590d0000547673171a001a0202491748281d4b47445e59655d5e104c12/926e6ef1cb221909334d8f7009a43893.html?affid=ac81902ea6025bafcfbdb8c515879b32,https://www.careerjet.com/job/926e6ef1cb221909334d8f7009a43893.html

In [5]:
from bs4 import BeautifulSoup as BS
import re

def finddesc(X):
    list = ['RevPro', 'SQL', 'tableau', 'Saas','python','Stata', 'Excel', 'Word', 'Power Point', 'Microsoft Office', 'CRM', 'Oracle', 'Enterprise', 'finance', 'cloud', 'big data', 'accounting', 'forecasting', 'computer science', 'statistics', 'economics', 'model','modeling', 'marketing','sales','hospitality','healthcare','business','food','logistic','operation','entertainment','human resources', 'MBA', 'Bachelor', 'masters','master','phd', 'degree']
    match=['SAS','R','POC','SAP','BS','BA','MS','MA','BA/BS','BS/BA', 'Java']
    list = [k.lower() for k in list]
    match = [k.lower() for k in match]
    keyword = []
    exp=[]
    num=""
    htmlfile = urllib.urlopen(X) 
    soup = BS(htmlfile,'html5lib')
    content_list=soup.find('div',attrs={'class':"main_job"})
    pretty=content_list.prettify()
    pretty1=pretty.lower()
    
    for i in list:
        if(pretty1.find(i, 0) > 0):
            keyword.append(i)
            
    for i in match: 
        if re.search(r"\b{}\b".format(i), pretty1, re.IGNORECASE) is not None:
            keyword.append(i)
            
    if re.search(r'\b(years)\b', pretty1) is not None: 
        a=re.search(r'\b(years)\b', pretty1)
        a=a.start()
        num=pretty1[(a-10):a]
        if "one" in num:
            num="1"
        if "two" in num:
            num="2"
        if "three" in num:
            num="3"
        if "four" in num:
            num="4"
        if "five" in num:
            num="5"
        if "six" in num:
            num="6"
        if "seven" in num:
            num="7"
        if "eight" in num:
            num="8"
        if "nine" in num:
            num="9"
        if "ten" in num:
            num="10"
        num=re.sub("[^0-9_-]", "", num)
        if "-" in num:
            num = num.split('-', 1)[1]
            if "-" in num:
                num = num.split('-', 1)[1]
        exp.append(num)
    
    keyword=keyword+exp
    
    return keyword
    
frame2=pd.DataFrame(NewDf,columns=['company','date','title','locations','salary','actual_link','description'])
x = []

for index, row in NewDf.iterrows():
    url = row['actual_link']
    description = finddesc(url)
    x.append(description)
frame2['description'] = x
frame2

,company,date,title,locations,salary,actual_link,description
0,Alamo Drafthouse Cinemas,"Fri, 30 Nov 2018 08:10:25 GMT",Benefits Analyst,"Austin, TX",,https://www.careerjet.com/job/14b492f081cdb7f15be85ebe0ab90838.html,"[excel, accounting, food, operation, degree, ms, 5]"
1,Direct Energy,"Thu, 13 Dec 2018 08:22:24 GMT",Senior Data Systems Analyst,"Houston, TX",,https://www.careerjet.com/job/84b6a31a6a269ca6f997f4e7def7228e.html,"[tableau, python, word, big data, computer science, statistics, model, modeling, marketing, business, logistic, bachelor, degree, r, java, 5]"
2,The Hunt Corporation,"Thu, 13 Dec 2018 08:58:58 GMT",Project Controls Analyst II,"Austin, TX",$100000 per year,https://www.careerjet.com/job/1c4a5837439a3551788b39d7fc93d68e.html,"[excel, word, business, bachelor, degree, r, ms, ma, 2]"
3,Ryder Logistics & Transportation,"Thu, 13 Dec 2018 08:52:22 GMT",Logistics Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/c5f1a1895a4bd1b7cf718e890230b49b.html,"[excel, word, business, logistic, operation, bachelor, degree, ms, 8]"
4,Maxim Government Services,"Thu, 06 Dec 2018 08:53:09 GMT",Board Certified Behavior Analyst BCBA,"Houston, TX",,https://www.careerjet.com/job/6652af1a4f32fd4e84a03f52abee1a44.html,"[model, healthcare, degree]"
5,Paccar,"Wed, 12 Dec 2018 08:36:21 GMT",IT Data Analyst Intern - Summer 2019 Job,"Denton, TX",,https://www.careerjet.com/job/554317ca9a128720def2a168abe27089.html,"[sql, python, excel, microsoft office, computer science, model, business, bachelor, degree, r, java]"
6,CPS Energy,"Wed, 12 Dec 2018 07:38:03 GMT",Data Engineer,"San Antonio, TX",,https://www.careerjet.com/job/90892ae46aded8abcfe4233390fc136c.html,"[sql, python, oracle, enterprise, cloud, big data, computer science, model, modeling, business, operation, human resources, bachelor, degree]"
7,NTT Data,"Thu, 13 Dec 2018 06:38:41 GMT",Clinical-Technical Help Desk Support Analyst,"Plano, TX",,https://www.careerjet.com/job/57dd18864359cd933a9dd925d258b34b.html,"[cloud, business, master, degree, 1]"
8,Bansar Technologies Inc,"Fri, 16 Nov 2018 08:14:29 GMT",Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/975c852d5ee3c69118c9e27d142364b0.html,"[sql, tableau, model, modeling, business]"
9,Bansar Technologies Inc,"Sun, 11 Nov 2018 08:52:22 GMT",Data Architect/Data Analyst,"Austin, TX",,https://www.careerjet.com/job/5293c054e9b6ff312bf0e545b45c775f.html,"[sql, oracle, model, modeling]"
10,,"Sun, 04 Nov 2018 08:40:47 GMT",Financial Analyst Lead,"Austin, TX",,https://www.careerjet.com/job/b4b9d6518853b7708d9883011f0ebc95.html,"[word, finance, accounting, model, business, operation, bachelor, master, degree, 7]"
11,Bansar Technologies Inc,"Mon, 05 Nov 2018 08:31:30 GMT",Senior Data Analyst,"Austin, TX",,https://www.careerjet.com/job/e731dd53e53b2f0dc8a73b7e14293dc4.html,"[sql, oracle]"
12,Targetbase,"Thu, 13 Dec 2018 08:21:38 GMT",Business Analyst,"Irving, TX",,https://www.careerjet.com/job/45f8e6c4843306b045c1f32b254e3be2.html,"[sql, excel, microsoft office, crm, model, modeling, marketing, sales, business, operation, bachelor, degree, 5]"
13,Targetbase,"Thu, 13 Dec 2018 08:20:15 GMT","Financial Analyst, Jr","Irving, TX",,https://www.careerjet.com/job/7f29aa140df358c273aa268b81002186.html,"[excel, microsoft office, finance, accounting, forecasting, economics, model, marketing, business, operation, bachelor, degree, ms, 3]"
14,Targetbase,"Thu, 13 Dec 2018 08:13:42 GMT","Analyst, Analytics","Irving, TX",,https://www.careerjet.com/job/1c8a6c2a4e12081438b892eca6d956dd.html,"[sql, python, excel, word, marketing, business, bachelor, masters, master, degree, sas, r, 4]"
15,NTT Data,"Wed, 21 Nov 2018 08:06:44 GMT",Senior Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/90544e861ae68a377b7a78f885b404f1.html,"[cloud, model, business, 5]"
16,NTT Data,"Wed, 21 Nov 2018 07:51:26 GMT",Senior Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/60fbf3d7f6ed89b700b32b027bfbdb85.html,"[cloud, model, business, 5]"
17,CyberCoders,"Thu, 13 Dec 2018 08:42:26 GMT",Senior Data Analyst,"Austin, TX",$120000 - 160000 per year,https://www.careerjet.com/job/1d42686ce46ee3fd51eb15c558cd6572.html,"[tableau, excel, big data, statistics, model, modeling, business, entertainment, bachelor, degree, r, 5]"
18,Robert Half,"Thu, 13 Dec 2018 08:11:34 GMT",Financial Data Analyst,"Plano, TX",$18 - 19 per hour,https://www.careerjet.com/job/01cc7b4c0267710c32cd3f6fbdc97eb7.html,"[excel, word, microsoft office, finance, accounting, economics, sales, business, master, sap, 6]"
19,Robert Half,"Thu, 13 Dec 2018 08:10:08 GMT",Data Reporting Analyst,"Dallas, TX",,https://www.careerjet.com/job/13068bec6d53419ebe13104b4688fb95.html,"[sql, python, excel, model, modeling, marketing, business, bachelor, degree, 65]"
20,Wits Solutions Inc,"Thu, 13 Dec 2018 07:49:00 GMT",Data Scientist - Senior Analyst Consultant,"Irving, TX",,https://www.careerjet.com/job/d99deef90c5eee6a2dea1d3d79dc0b95.html,"[python, cloud, computer science, business, bachelor, degree, sas, r, ]"
21,ReqRoute,"Thu, 13 Dec 2018 06:52:35 GMT",9063 BI Data Analyst,"Plano, TX",,https://www.careerjet.com/job/04589cac227c6607a365c5ed6cc37f3e.html,"[sql, business]"
22,St Joseph Health System,"Thu, 13 Dec 2018 06:20:01 GMT",Clinical Data Analyst,"Lubbock, TX",,https://www.careerjet.com/job/37d54198098f1121c00e1b44fb011601.html,"[sql, excel, model, modeling, healthcare, business, operation, bachelor, degree, 3]"
23,Robert Half,"Thu, 13 Dec 2018 04:58:15 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,https://www.careerjet.com/job/01907084254c2e9f47edc3eff67468ca.html,"[excel, sales, business, bachelor, degree, 5]"
24,Dow,"Thu, 13 Dec 2018 04:09:26 GMT",Production Data Analyst,"Texas City, TX",,https://www.careerjet.com/job/70f7e5d64607db11f9e713a86c46b12c.html,"[excel, finance, accounting, forecasting, business, operation, master, sap, 2]"
25,Atrilogy,"Thu, 13 Dec 2018 03:31:11 GMT",BI Data Analyst,"Westlake, TX",,https://www.careerjet.com/job/b7096e743e5951bdb1a4f268c9d9949a.html,"[sql, excel, word, crm, oracle, big data, model, sales, business, masters, master, degree, sap]"
26,Robert Half,"Thu, 13 Dec 2018 02:44:26 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,https://www.careerjet.com/job/cfe4cc5509c5a470521d248bd534db32.html,"[excel, sales, business, bachelor, degree, 5]"
27,North Texas LEAD,"Thu, 13 Dec 2018 00:48:22 GMT",IT Business Systems Data Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/35a13e7b1b191d3efc13b80b8f512156.html,"[sql, excel, microsoft office, computer science, business, operation, bachelor, degree]"
28,CVS Health,"Thu, 13 Dec 2018 00:15:48 GMT",Sr Analyst Data Warehouse,"Richardson, TX",,https://www.careerjet.com/job/3b5656afe42d2602b51f15fe4e386719.html,"[python, excel, enterprise, big data, computer science, business, bachelor, degree, 3]"
29,Chevron,"Wed, 12 Dec 2018 23:54:57 GMT",S&T- Market Data Analyst,"Houston, TX",,https://www.careerjet.com/job/8a6cd08d613a79ce6766c9961804136c.html,"[business, bachelor, degree, 8]"
...,...,...,...,...,...,...,...
50,Cenpatico,"Sat, 08 Dec 2018 08:14:59 GMT",Business Analyst II(Healthcare Data,"Austin, TX",,https://www.careerjet.com/job/bff6ad4c48679b97d7e0cd3da23bc717.html,"[sql, excel, healthcare, business, operation, bachelor, degree, 4]"
51,Cheniere,"Sat, 08 Dec 2018 07:17:38 GMT",Health and Safety Data Analyst,"Houston, TX",,https://www.careerjet.com/job/fe3e5e4701057eda33528c26757cdfdf.html,"[excel, microsoft office, enterprise, business, operation, bachelor, degree, ]"
52,,"Sat, 08 Dec 2018 01:25:54 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/cf91099fed241f07d51ec9dafed501aa.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]"
53,Robert Half,"Sat, 08 Dec 2018 00:13:30 GMT",Data Analyst,"San Antonio, TX",$25 - 27 per hour,https://www.careerjet.com/job/9d89c5b04bedd12ae4c24cc278ca7886.html,"[excel, word, oracle, finance, accounting, master, sap]"
54,Textron,"Sat, 08 Dec 2018 00:10:22 GMT",Data Analyst (V-247Program),"Fort Worth, TX",,https://www.careerjet.com/job/94a74f362462282297db8b3e9536d475.html,"[excel, finance, accounting, business, bachelor, degree, sap, ms, 2]"
55,Saxon Global,"Fri, 07 Dec 2018 23:52:58 GMT","Senior Data Analyst Developer (SSIS, SSRS)","San Antonio, TX",,https://www.careerjet.com/job/e7895c514f0ab58aa35e9e3ac86369be.html,[]
56,Princeton Information,"Fri, 07 Dec 2018 23:51:06 GMT",Data Analyst - III,"Dallas, TX",$48.64 - 65.67 per hour,https://www.careerjet.com/job/66b564baf28e500c88eb15f18b818229.html,"[sql, tableau, word, big data, statistics, economics, model, modeling, business, bachelor, master, degree, 5]"
57,CornerStone Staffing,"Fri, 07 Dec 2018 23:45:31 GMT",Data Analyst,"Richardson, TX",$24 per hour,https://www.careerjet.com/job/0a296d21088bc8c6f5b43b7fa590803a.html,"[sql, excel, word, ms, 2]"
58,TechnipFMC,"Fri, 07 Dec 2018 23:03:43 GMT",Data Support Analyst,"Houston, TX",,https://www.careerjet.com/job/ff10336f6b5f898ba2bbc2ce5f61440c.html,"[oracle, computer science, business, ]"
59,Advantage Resourcing,"Fri, 07 Dec 2018 08:53:33 GMT",Data Analyst,"Round Rock, TX",,https://www.careerjet.com/job/3d383317ec95a416bba3d964910a7349.html,"[tableau, excel, finance, accounting, sales]"
60,McKesson Technologies Limited,"Fri, 07 Dec 2018 08:50:32 GMT",Data Management Analyst,"Irving, TX",,https://www.careerjet.com/job/7fe62b912a8c652874633cc9ec74fb71.html,"[sql, excel, healthcare, business, operation, master, degree, ms, 2]"
61,Endurix,"Fri, 07 Dec 2018 08:49:51 GMT",HR Data Analyst,"Dallas, TX",,https://www.careerjet.com/job/fd164df8f748f97ec4afdcfcfde01629.html,"[sql, excel, finance, model, business, human resources, master, degree]"
62,,"Fri, 07 Dec 2018 08:37:49 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/e2bca52a3d745f599ceb460ac512a719.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]"
63,EPMA,"Fri, 07 Dec 2018 08:27:22 GMT",Data Analyst,"Addison, TX",,https://www.careerjet.com/job/75ede1521a4ee84d61a78b58ff5a7f2d.html,"[excel, microsoft office, computer science, business, degree, 3]"
64,Verveba Analytics,"Fri, 07 Dec 2018 08:24:26 GMT",Data Analyst/ Hadoop developer,"Richardson, TX",,https://www.careerjet.com/job/015f4650bba10c8394f017bb9809fcfb.html,"[python, cloud, big data, computer science, model, modeling, business, human resources, bachelor, degree, sas, r, java, 3]"
65,Statera,"Fri, 07 Dec 2018 07:50:25 GMT",Data Analyst - CTH - Dallas,"Dallas, TX",,https://www.careerjet.com/job/34702c994b2cceca7b3a7f92437e2046.html,"[sql, excel, big data, computer science, statistics, economics, model, business, bachelor, degree, sas, 3]"
66,,"Fri, 07 Dec 2018 06:29:55 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/8fd0ad47077b0885f31650dbcb2f7440.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]"
67,,"Fri, 07 Dec 2018 04:57:12 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/926e6ef1cb221909334d8f7009a43893.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]"
68,Texas A&M University,"Fri, 07 Dec 2018 04:41:44 GMT",Data Analyst,"College Station, TX",,https://www.careerjet.com/job/aa9e1faa1902dcdeac1e78b849b1ef5a.html,"[excel, word, microsoft office, bachelor, degree, 3]"
69,Spectrum,"Thu, 06 Dec 2018 23:06:27 GMT",Bus Data Analyst-Call Analytic,"Austin, TX",,https://www.careerjet.com/job/f509658f5538aa61073a0008db463231.html,"[sql, word, oracle, enterprise, accounting, statistics, economics, business, operation, bachelor, degree, 3]"
70,USAA,"Thu, 06 Dec 2018 08:58:51 GMT",Data Quality Analyst I,"San Antonio, TX",,https://www.careerjet.com/job/9815c57f34e7624cb0373019ff5b308d.html,"[sql, enterprise, model, business, bachelor, master, phd, degree, sas, ]"
71,,"Thu, 06 Dec 2018 08:55:31 GMT",TAR-Data Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/bb4ab960510cdd063f9ea0e2320b9374.html,"[sql, excel, microsoft office, business, bachelor, degree, 2]"
72,,"Thu, 06 Dec 2018 08:49:01 GMT",Data Services Analyst,"Dallas, TX",,https://www.careerjet.com/job/6c1db282a97c7997a26b4252d79cc003.html,"[sql, finance, operation, bachelor, degree, ms, 2]"
73,,"Thu, 06 Dec 2018 08:43:05 GMT",Data Analyst,"Frisco, TX",,https://www.careerjet.com/job/d0f0091fffdc0d3907c3221e85aca54a.html,"[sql, python, excel, microsoft office, computer science, statistics, business, operation, bachelor, degree, r, ms, java, 2]"
74,Bank of America,"Thu, 06 Dec 2018 06:42:29 GMT",Data Analyst,"Plano, TX",,https://www.careerjet.com/job/c3cdbba9ac3e1ac26d175ed874430eae.html,"[sql, python, excel, statistics, business, degree, r, 5]"
75,,"Thu, 06 Dec 2018 01:44:20 GMT",Data / Systems Business Analyst II,"Irving, TX",,https://www.careerjet.com/job/7e151125afb3dd2662af02f556601bc3.html,"[sql, excel, word, healthcare, business, bachelor, degree, java, 3]"
76,DSI Systems,"Wed, 05 Dec 2018 23:56:33 GMT",Data Analyst,"Richardson, TX",,https://www.careerjet.com/job/834de28146cf7bfd5cd8ba379c9dc48e.html,"[sql, excel, crm, sales, business, operation, bachelor, degree, 3]"
77,IT Trailblazers LLC,"Wed, 05 Dec 2018 23:08:05 GMT",Senior Business Analyst Business Analyst (Data Transformation),"Plano, TX",,https://www.careerjet.com/job/aeb572b85a2dc5960fd67391479daf92.html,"[business, master]"
78,Creditserve,"Wed, 05 Dec 2018 08:59:43 GMT",Data / Business Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/66319dcf17f7a611701ee1c8b6fa505e.html,"[sql, excel, word, microsoft office, model, marketing, business, sas, 7]"
79,Creditserve,"Wed, 05 Dec 2018 08:51:11 GMT",Data / Business Analyst,"Austin, TX",,https://www.careerjet.com/job/13b24cd13e18ee6d89bfb7cf76e92aa2.html,"[sql, excel, word, microsoft office, model, marketing, business, sas, 7]"

In [6]:
list1 = ['RevPro', 'SQL', 'tableau', 'Saas','SAS','R','POC','SAP','python','Stata', 'Excel','Java', 'Word', 'Power Point', 'Microsoft Office', 'CRM', 'Oracle', 'Enterprise', 'finance', 'cloud', 'big data', 'accounting', 'forecasting', 'computer science', 'statistics', 'economics', 'model','modeling', 'marketing','sales','hospitality','entertainment','healthcare','business','food','logistic','operation','human resources', 'MBA', 'Bachelor', 'masters','master','phd','degree','BS','BA','MS','MA','BA/BS','BS/BA']
list1 = [k.lower() for k in list1]
final_df = pd.DataFrame(index = frame2.index, columns = list1)
final_df['description'] = frame2['description']
desc = final_df['description']
z = 0
for i in desc:
    for skill in i:
        final_df.loc[z, skill] = 1
    z += 1
final_df = final_df.fillna(0)
final_df

,revpro,sql,tableau,saas,sas,r,poc,sap,python,stata,...,5,2,8,1,7,3,4,6,65,
0,0,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,1,0,0,1,0,0,1,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0,0,0,0,1,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0,1,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0,1,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0,1,1,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0,1,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14,0,1,0,0,1,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15,0,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0,0,1,0,0,1,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0,0,0,0,0,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19,0,1,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
20,0,0,0,0,1,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
21,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
23,0,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0,0,0,0,0,0,0,1,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0,1,0,0,0,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0,0,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
29,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
51,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
52,0,1,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,0,0,0,0,0,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,0,0,0,0,0,0,0,1,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56,0,1,1,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57,0,1,0,0,0,0,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
59,0,0,1,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60,0,1,0,0,0,0,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,0,1,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
64,0,0,0,0,1,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
65,0,1,0,0,1,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
66,0,1,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,0,1,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
68,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
69,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
70,0,1,0,0,1,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
71,0,1,0,0,0,0,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,0,1,0,0,0,0,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,0,1,0,0,0,1,0,0,1,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74,0,1,0,0,0,1,0,0,1,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
76,0,1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
77,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78,0,1,0,0,1,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
79,0,1,0,0,1,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [7]:
pd.set_option('display.max_colwidth', -1) #expand full columns
final_df=final_df.drop(columns=['description'])
frames = [frame2, final_df]
result = pd.concat(frames, axis = 1)
result

,company,date,title,locations,salary,actual_link,description,revpro,sql,tableau,...,5,2,8,1,7,3,4,6,65,
0,Alamo Drafthouse Cinemas,"Fri, 30 Nov 2018 08:10:25 GMT",Benefits Analyst,"Austin, TX",,https://www.careerjet.com/job/14b492f081cdb7f15be85ebe0ab90838.html,"[excel, accounting, food, operation, degree, ms, 5]",0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Direct Energy,"Thu, 13 Dec 2018 08:22:24 GMT",Senior Data Systems Analyst,"Houston, TX",,https://www.careerjet.com/job/84b6a31a6a269ca6f997f4e7def7228e.html,"[tableau, python, word, big data, computer science, statistics, model, modeling, marketing, business, logistic, bachelor, degree, r, java, 5]",0,0,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,The Hunt Corporation,"Thu, 13 Dec 2018 08:58:58 GMT",Project Controls Analyst II,"Austin, TX",$100000 per year,https://www.careerjet.com/job/1c4a5837439a3551788b39d7fc93d68e.html,"[excel, word, business, bachelor, degree, r, ms, ma, 2]",0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Ryder Logistics & Transportation,"Thu, 13 Dec 2018 08:52:22 GMT",Logistics Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/c5f1a1895a4bd1b7cf718e890230b49b.html,"[excel, word, business, logistic, operation, bachelor, degree, ms, 8]",0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Maxim Government Services,"Thu, 06 Dec 2018 08:53:09 GMT",Board Certified Behavior Analyst BCBA,"Houston, TX",,https://www.careerjet.com/job/6652af1a4f32fd4e84a03f52abee1a44.html,"[model, healthcare, degree]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Paccar,"Wed, 12 Dec 2018 08:36:21 GMT",IT Data Analyst Intern - Summer 2019 Job,"Denton, TX",,https://www.careerjet.com/job/554317ca9a128720def2a168abe27089.html,"[sql, python, excel, microsoft office, computer science, model, business, bachelor, degree, r, java]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,CPS Energy,"Wed, 12 Dec 2018 07:38:03 GMT",Data Engineer,"San Antonio, TX",,https://www.careerjet.com/job/90892ae46aded8abcfe4233390fc136c.html,"[sql, python, oracle, enterprise, cloud, big data, computer science, model, modeling, business, operation, human resources, bachelor, degree]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,NTT Data,"Thu, 13 Dec 2018 06:38:41 GMT",Clinical-Technical Help Desk Support Analyst,"Plano, TX",,https://www.careerjet.com/job/57dd18864359cd933a9dd925d258b34b.html,"[cloud, business, master, degree, 1]",0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Bansar Technologies Inc,"Fri, 16 Nov 2018 08:14:29 GMT",Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/975c852d5ee3c69118c9e27d142364b0.html,"[sql, tableau, model, modeling, business]",0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Bansar Technologies Inc,"Sun, 11 Nov 2018 08:52:22 GMT",Data Architect/Data Analyst,"Austin, TX",,https://www.careerjet.com/job/5293c054e9b6ff312bf0e545b45c775f.html,"[sql, oracle, model, modeling]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,,"Sun, 04 Nov 2018 08:40:47 GMT",Financial Analyst Lead,"Austin, TX",,https://www.careerjet.com/job/b4b9d6518853b7708d9883011f0ebc95.html,"[word, finance, accounting, model, business, operation, bachelor, master, degree, 7]",0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,Bansar Technologies Inc,"Mon, 05 Nov 2018 08:31:30 GMT",Senior Data Analyst,"Austin, TX",,https://www.careerjet.com/job/e731dd53e53b2f0dc8a73b7e14293dc4.html,"[sql, oracle]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Targetbase,"Thu, 13 Dec 2018 08:21:38 GMT",Business Analyst,"Irving, TX",,https://www.careerjet.com/job/45f8e6c4843306b045c1f32b254e3be2.html,"[sql, excel, microsoft office, crm, model, modeling, marketing, sales, business, operation, bachelor, degree, 5]",0,1,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Targetbase,"Thu, 13 Dec 2018 08:20:15 GMT","Financial Analyst, Jr","Irving, TX",,https://www.careerjet.com/job/7f29aa140df358c273aa268b81002186.html,"[excel, microsoft office, finance, accounting, forecasting, economics, model, marketing, business, operation, bachelor, degree, ms, 3]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14,Targetbase,"Thu, 13 Dec 2018 08:13:42 GMT","Analyst, Analytics","Irving, TX",,https://www.careerjet.com/job/1c8a6c2a4e12081438b892eca6d956dd.html,"[sql, python, excel, word, marketing, business, bachelor, masters, master, degree, sas, r, 4]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15,NTT Data,"Wed, 21 Nov 2018 08:06:44 GMT",Senior Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/90544e861ae68a377b7a78f885b404f1.html,"[cloud, model, business, 5]",0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,NTT Data,"Wed, 21 Nov 2018 07:51:26 GMT",Senior Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/60fbf3d7f6ed89b700b32b027bfbdb85.html,"[cloud, model, business, 5]",0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,CyberCoders,"Thu, 13 Dec 2018 08:42:26 GMT",Senior Data Analyst,"Austin, TX",$120000 - 160000 per year,https://www.careerjet.com/job/1d42686ce46ee3fd51eb15c558cd6572.html,"[tableau, excel, big data, statistics, model, modeling, business, entertainment, bachelor, degree, r, 5]",0,0,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Robert Half,"Thu, 13 Dec 2018 08:11:34 GMT",Financial Data Analyst,"Plano, TX",$18 - 19 per hour,https://www.careerjet.com/job/01cc7b4c0267710c32cd3f6fbdc97eb7.html,"[excel, word, microsoft office, finance, accounting, economics, sales, business, master, sap, 6]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19,Robert Half,"Thu, 13 Dec 2018 08:10:08 GMT",Data Reporting Analyst,"Dallas, TX",,https://www.careerjet.com/job/13068bec6d53419ebe13104b4688fb95.html,"[sql, python, excel, model, modeling, marketing, business, bachelor, degree, 65]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
20,Wits Solutions Inc,"Thu, 13 Dec 2018 07:49:00 GMT",Data Scientist - Senior Analyst Consultant,"Irving, TX",,https://www.careerjet.com/job/d99deef90c5eee6a2dea1d3d79dc0b95.html,"[python, cloud, computer science, business, bachelor, degree, sas, r, ]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
21,ReqRoute,"Thu, 13 Dec 2018 06:52:35 GMT",9063 BI Data Analyst,"Plano, TX",,https://www.careerjet.com/job/04589cac227c6607a365c5ed6cc37f3e.html,"[sql, business]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,St Joseph Health System,"Thu, 13 Dec 2018 06:20:01 GMT",Clinical Data Analyst,"Lubbock, TX",,https://www.careerjet.com/job/37d54198098f1121c00e1b44fb011601.html,"[sql, excel, model, modeling, healthcare, business, operation, bachelor, degree, 3]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
23,Robert Half,"Thu, 13 Dec 2018 04:58:15 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,https://www.careerjet.com/job/01907084254c2e9f47edc3eff67468ca.html,"[excel, sales, business, bachelor, degree, 5]",0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,Dow,"Thu, 13 Dec 2018 04:09:26 GMT",Production Data Analyst,"Texas City, TX",,https://www.careerjet.com/job/70f7e5d64607db11f9e713a86c46b12c.html,"[excel, finance, accounting, forecasting, business, operation, master, sap, 2]",0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,Atrilogy,"Thu, 13 Dec 2018 03:31:11 GMT",BI Data Analyst,"Westlake, TX",,https://www.careerjet.com/job/b7096e743e5951bdb1a4f268c9d9949a.html,"[sql, excel, word, crm, oracle, big data, model, sales, business, masters, master, degree, sap]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,Robert Half,"Thu, 13 Dec 2018 02:44:26 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,https://www.careerjet.com/job/cfe4cc5509c5a470521d248bd534db32.html,"[excel, sales, business, bachelor, degree, 5]",0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,North Texas LEAD,"Thu, 13 Dec 2018 00:48:22 GMT",IT Business Systems Data Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/35a13e7b1b191d3efc13b80b8f512156.html,"[sql, excel, microsoft office, computer science, business, operation, bachelor, degree]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,CVS Health,"Thu, 13 Dec 2018 00:15:48 GMT",Sr Analyst Data Warehouse,"Richardson, TX",,https://www.careerjet.com/job/3b5656afe42d2602b51f15fe4e386719.html,"[python, excel, enterprise, big data, computer science, business, bachelor, degree, 3]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
29,Chevron,"Wed, 12 Dec 2018 23:54:57 GMT",S&T- Market Data Analyst,"Houston, TX",,https://www.careerjet.com/job/8a6cd08d613a79ce6766c9961804136c.html,"[business, bachelor, degree, 8]",0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,Cenpatico,"Sat, 08 Dec 2018 08:14:59 GMT",Business Analyst II(Healthcare Data,"Austin, TX",,https://www.careerjet.com/job/bff6ad4c48679b97d7e0cd3da23bc717.html,"[sql, excel, healthcare, business, operation, bachelor, degree, 4]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
51,Cheniere,"Sat, 08 Dec 2018 07:17:38 GMT",Health and Safety Data Analyst,"Houston, TX",,https://www.careerjet.com/job/fe3e5e4701057eda33528c26757cdfdf.html,"[excel, microsoft office, enterprise, business, operation, bachelor, degree, ]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
52,,"Sat, 08 Dec 2018 01:25:54 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/cf91099fed241f07d51ec9dafed501aa.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,Robert Half,"Sat, 08 Dec 2018 00:13:30 GMT",Data Analyst,"San Antonio, TX",$25 - 27 per hour,https://www.careerjet.com/job/9d89c5b04bedd12ae4c24cc278ca7886.html,"[excel, word, oracle, finance, accounting, master, sap]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,Textron,"Sat, 08 Dec 2018 00:10:22 GMT",Data Analyst (V-247Program),"Fort Worth, TX",,https://www.careerjet.com/job/94a74f362462282297db8b3e9536d475.html,"[excel, finance, accounting, business, bachelor, degree, sap, ms, 2]",0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,Saxon Global,"Fri, 07 Dec 2018 23:52:58 GMT","Senior Data Analyst Developer (SSIS, SSRS)","San Antonio, TX",,https://www.careerjet.com/job/e7895c514f0ab58aa35e9e3ac86369be.html,[],0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56,Princeton Information,"Fri, 07 Dec 2018 23:51:06 GMT",Data Analyst - III,"Dallas, TX",$48.64 - 65.67 per hour,https://www.careerjet.com/job/66b564baf28e500c88eb15f18b818229.html,"[sql, tableau, word, big data, statistics, economics, model, modeling, business, bachelor, master, degree, 5]",0,1,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57,CornerStone Staffing,"Fri, 07 Dec 2018 23:45:31 GMT",Data Analyst,"Richardson, TX",$24 per hour,https://www.careerjet.com/job/0a296d21088bc8c6f5b43b7fa590803a.html,"[sql, excel, word, ms, 2]",0,1,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,TechnipFMC,"Fri, 07 Dec 2018 23:03:43 GMT",Data Support Analyst,"Houston, TX",,https://www.careerjet.com/job/ff10336f6b5f898ba2bbc2ce5f61440c.html,"[oracle, computer science, business, ]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
59,Advantage Resourcing,"Fri, 07 Dec 2018 08:53:33 GMT",Data Analyst,"Round Rock, TX",,https://www.careerjet.com/job/3d383317ec95a416bba3d964910a7349.html,"[tableau, excel, finance, accounting, sales]",0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60,McKesson Technologies Limited,"Fri, 07 Dec 2018 08:50:32 GMT",Data Management Analyst,"Irving, TX",,https://www.careerjet.com/job/7fe62b912a8c652874633cc9ec74fb71.html,"[sql, excel, healthcare, business, operation, master, degree, ms, 2]",0,1,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,Endurix,"Fri, 07 Dec 2018 08:49:51 GMT",HR Data Analyst,"Dallas, TX",,https://www.careerjet.com/job/fd164df8f748f97ec4afdcfcfde01629.html,"[sql, excel, finance, model, business, human resources, master, degree]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,,"Fri, 07 Dec 2018 08:37:49 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/e2bca52a3d745f599ceb460ac512a719.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,EPMA,"Fri, 07 Dec 2018 08:27:22 GMT",Data Analyst,"Addison, TX",,https://www.careerjet.com/job/75ede1521a4ee84d61a78b58ff5a7f2d.html,"[excel, microsoft office, computer science, business, degree, 3]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
64,Verveba Analytics,"Fri, 07 Dec 2018 08:24:26 GMT",Data Analyst/ Hadoop developer,"Richardson, TX",,https://www.careerjet.com/job/015f4650bba10c8394f017bb9809fcfb.html,"[python, cloud, big data, computer science, model, modeling, business, human resources, bachelor, degree, sas, r, java, 3]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
65,Statera,"Fri, 07 Dec 2018 07:50:25 GMT",Data Analyst - CTH - Dallas,"Dallas, TX",,https://www.careerjet.com/job/34702c994b2cceca7b3a7f92437e2046.html,"[sql, excel, big data, computer science, statistics, economics, model, business, bachelor, degree, sas, 3]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
66,,"Fri, 07 Dec 2018 06:29:55 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/8fd0ad47077b0885f31650dbcb2f7440.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,,"Fri, 07 Dec 2018 04:57:12 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/926e6ef1cb221909334d8f7009a43893.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
68,Texas A&M University,"Fri, 07 Dec 2018 04:41:44 GMT",Data Analyst,"College Station, TX",,https://www.careerjet.com/job/aa9e1faa1902dcdeac1e78b849b1ef5a.html,"[excel, word, microsoft office, bachelor, degree, 3]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
69,Spectrum,"Thu, 06 Dec 2018 23:06:27 GMT",Bus Data Analyst-Call Analytic,"Austin, TX",,https://www.careerjet.com/job/f509658f5538aa61073a0008db463231.html,"[sql, word, oracle, enterprise, accounting, statistics, economics, business, operation, bachelor, degree, 3]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
70,USAA,"Thu, 06 Dec 2018 08:58:51 GMT",Data Quality Analyst I,"San Antonio, TX",,https://www.careerjet.com/job/9815c57f34e7624cb0373019ff5b308d.html,"[sql, enterprise, model, business, bachelor, master, phd, degree, sas, ]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
71,,"Thu, 06 Dec 2018 08:55:31 GMT",TAR-Data Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/bb4ab960510cdd063f9ea0e2320b9374.html,"[sql, excel, microsoft office, business, bachelor, degree, 2]",0,1,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,,"Thu, 06 Dec 2018 08:49:01 GMT",Data Services Analyst,"Dallas, TX",,https://www.careerjet.com/job/6c1db282a97c7997a26b4252d79cc003.html,"[sql, finance, operation, bachelor, degree, ms, 2]",0,1,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,,"Thu, 06 Dec 2018 08:43:05 GMT",Data Analyst,"Frisco, TX",,https://www.careerjet.com/job/d0f0091fffdc0d3907c3221e85aca54a.html,"[sql, python, excel, microsoft office, computer science, statistics, business, operation, bachelor, degree, r, ms, java, 2]",0,1,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74,Bank of America,"Thu, 06 Dec 2018 06:42:29 GMT",Data Analyst,"Plano, TX",,https://www.careerjet.com/job/c3cdbba9ac3e1ac26d175ed874430eae.html,"[sql, python, excel, statistics, business, degree, r, 5]",0,1,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75,,"Thu, 06 Dec 2018 01:44:20 GMT",Data / Systems Business Analyst II,"Irving, TX",,https://www.careerjet.com/job/7e151125afb3dd2662af02f556601bc3.html,"[sql, excel, word, healthcare, business, bachelor, degree, java, 3]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
76,DSI Systems,"Wed, 05 Dec 2018 23:56:33 GMT",Data Analyst,"Richardson, TX",,https://www.careerjet.com/job/834de28146cf7bfd5cd8ba379c9dc48e.html,"[sql, excel, crm, sales, business, operation, bachelor, degree, 3]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
77,IT Trailblazers LLC,"Wed, 05 Dec 2018 23:08:05 GMT",Senior Business Analyst Business Analyst (Data Transformation),"Plano, TX",,https://www.careerjet.com/job/aeb572b85a2dc5960fd67391479daf92.html,"[business, master]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78,Creditserve,"Wed, 05 Dec 2018 08:59:43 GMT",Data / Business Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/66319dcf17f7a611701ee1c8b6fa505e.html,"[sql, excel, word, microsoft office, model, marketing, business, sas, 7]",0,1,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
79,Creditserve,"Wed, 05 Dec 2018 08:51:11 GMT",Data / Business Analyst,"Austin, TX",,https://www.careerjet.com/job/13b24cd13e18ee6d89bfb7cf76e92aa2.html,"[sql, excel, word, microsoft office, model, marketing, business, sas, 7]",0,1,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [8]:
#result=result.drop(columns=['Bachelor'])
result['Bachelor'] = np.where((result['ba']==1) | (result['bs']==1) | (result['ba/bs']==1) | (result['bs/ba']==1) | (result['bachelor']==1),1,0)
result['Master'] = np.where((result['ma']==1) | (result['ms']==1) | (result['master']==1) | (result["masters"]==1) | (result['mba']==1),1,0)
result

,company,date,title,locations,salary,actual_link,description,revpro,sql,tableau,...,8,1,7,3,4,6,65,,Bachelor,Master
0,Alamo Drafthouse Cinemas,"Fri, 30 Nov 2018 08:10:25 GMT",Benefits Analyst,"Austin, TX",,https://www.careerjet.com/job/14b492f081cdb7f15be85ebe0ab90838.html,"[excel, accounting, food, operation, degree, ms, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
1,Direct Energy,"Thu, 13 Dec 2018 08:22:24 GMT",Senior Data Systems Analyst,"Houston, TX",,https://www.careerjet.com/job/84b6a31a6a269ca6f997f4e7def7228e.html,"[tableau, python, word, big data, computer science, statistics, model, modeling, marketing, business, logistic, bachelor, degree, r, java, 5]",0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
2,The Hunt Corporation,"Thu, 13 Dec 2018 08:58:58 GMT",Project Controls Analyst II,"Austin, TX",$100000 per year,https://www.careerjet.com/job/1c4a5837439a3551788b39d7fc93d68e.html,"[excel, word, business, bachelor, degree, r, ms, ma, 2]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
3,Ryder Logistics & Transportation,"Thu, 13 Dec 2018 08:52:22 GMT",Logistics Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/c5f1a1895a4bd1b7cf718e890230b49b.html,"[excel, word, business, logistic, operation, bachelor, degree, ms, 8]",0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
4,Maxim Government Services,"Thu, 06 Dec 2018 08:53:09 GMT",Board Certified Behavior Analyst BCBA,"Houston, TX",,https://www.careerjet.com/job/6652af1a4f32fd4e84a03f52abee1a44.html,"[model, healthcare, degree]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
5,Paccar,"Wed, 12 Dec 2018 08:36:21 GMT",IT Data Analyst Intern - Summer 2019 Job,"Denton, TX",,https://www.careerjet.com/job/554317ca9a128720def2a168abe27089.html,"[sql, python, excel, microsoft office, computer science, model, business, bachelor, degree, r, java]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
6,CPS Energy,"Wed, 12 Dec 2018 07:38:03 GMT",Data Engineer,"San Antonio, TX",,https://www.careerjet.com/job/90892ae46aded8abcfe4233390fc136c.html,"[sql, python, oracle, enterprise, cloud, big data, computer science, model, modeling, business, operation, human resources, bachelor, degree]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
7,NTT Data,"Thu, 13 Dec 2018 06:38:41 GMT",Clinical-Technical Help Desk Support Analyst,"Plano, TX",,https://www.careerjet.com/job/57dd18864359cd933a9dd925d258b34b.html,"[cloud, business, master, degree, 1]",0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
8,Bansar Technologies Inc,"Fri, 16 Nov 2018 08:14:29 GMT",Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/975c852d5ee3c69118c9e27d142364b0.html,"[sql, tableau, model, modeling, business]",0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
9,Bansar Technologies Inc,"Sun, 11 Nov 2018 08:52:22 GMT",Data Architect/Data Analyst,"Austin, TX",,https://www.careerjet.com/job/5293c054e9b6ff312bf0e545b45c775f.html,"[sql, oracle, model, modeling]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
10,,"Sun, 04 Nov 2018 08:40:47 GMT",Financial Analyst Lead,"Austin, TX",,https://www.careerjet.com/job/b4b9d6518853b7708d9883011f0ebc95.html,"[word, finance, accounting, model, business, operation, bachelor, master, degree, 7]",0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,1
11,Bansar Technologies Inc,"Mon, 05 Nov 2018 08:31:30 GMT",Senior Data Analyst,"Austin, TX",,https://www.careerjet.com/job/e731dd53e53b2f0dc8a73b7e14293dc4.html,"[sql, oracle]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
12,Targetbase,"Thu, 13 Dec 2018 08:21:38 GMT",Business Analyst,"Irving, TX",,https://www.careerjet.com/job/45f8e6c4843306b045c1f32b254e3be2.html,"[sql, excel, microsoft office, crm, model, modeling, marketing, sales, business, operation, bachelor, degree, 5]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
13,Targetbase,"Thu, 13 Dec 2018 08:20:15 GMT","Financial Analyst, Jr","Irving, TX",,https://www.careerjet.com/job/7f29aa140df358c273aa268b81002186.html,"[excel, microsoft office, finance, accounting, forecasting, economics, model, marketing, business, operation, bachelor, degree, ms, 3]",0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1
14,Targetbase,"Thu, 13 Dec 2018 08:13:42 GMT","Analyst, Analytics","Irving, TX",,https://www.careerjet.com/job/1c8a6c2a4e12081438b892eca6d956dd.html,"[sql, python, excel, word, marketing, business, bachelor, masters, master, degree, sas, r, 4]",0,1,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,1
15,NTT Data,"Wed, 21 Nov 2018 08:06:44 GMT",Senior Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/90544e861ae68a377b7a78f885b404f1.html,"[cloud, model, business, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
16,NTT Data,"Wed, 21 Nov 2018 07:51:26 GMT",Senior Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/60fbf3d7f6ed89b700b32b027bfbdb85.html,"[cloud, model, business, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
17,CyberCoders,"Thu, 13 Dec 2018 08:42:26 GMT",Senior Data Analyst,"Austin, TX",$120000 - 160000 per year,https://www.careerjet.com/job/1d42686ce46ee3fd51eb15c558cd6572.html,"[tableau, excel, big data, statistics, model, modeling, business, entertainment, bachelor, degree, r, 5]",0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
18,Robert Half,"Thu, 13 Dec 2018 08:11:34 GMT",Financial Data Analyst,"Plano, TX",$18 - 19 per hour,https://www.careerjet.com/job/01cc7b4c0267710c32cd3f6fbdc97eb7.html,"[excel, word, microsoft office, finance, accounting, economics, sales, business, master, sap, 6]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,1
19,Robert Half,"Thu, 13 Dec 2018 08:10:08 GMT",Data Reporting Analyst,"Dallas, TX",,https://www.careerjet.com/job/13068bec6d53419ebe13104b4688fb95.html,"[sql, python, excel, model, modeling, marketing, business, bachelor, degree, 65]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0
20,Wits Solutions Inc,"Thu, 13 Dec 2018 07:49:00 GMT",Data Scientist - Senior Analyst Consultant,"Irving, TX",,https://www.careerjet.com/job/d99deef90c5eee6a2dea1d3d79dc0b95.html,"[python, cloud, computer science, business, bachelor, degree, sas, r, ]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,0
21,ReqRoute,"Thu, 13 Dec 2018 06:52:35 GMT",9063 BI Data Analyst,"Plano, TX",,https://www.careerjet.com/job/04589cac227c6607a365c5ed6cc37f3e.html,"[sql, business]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
22,St Joseph Health System,"Thu, 13 Dec 2018 06:20:01 GMT",Clinical Data Analyst,"Lubbock, TX",,https://www.careerjet.com/job/37d54198098f1121c00e1b44fb011601.html,"[sql, excel, model, modeling, healthcare, business, operation, bachelor, degree, 3]",0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0
23,Robert Half,"Thu, 13 Dec 2018 04:58:15 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,https://www.careerjet.com/job/01907084254c2e9f47edc3eff67468ca.html,"[excel, sales, business, bachelor, degree, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
24,Dow,"Thu, 13 Dec 2018 04:09:26 GMT",Production Data Analyst,"Texas City, TX",,https://www.careerjet.com/job/70f7e5d64607db11f9e713a86c46b12c.html,"[excel, finance, accounting, forecasting, business, operation, master, sap, 2]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
25,Atrilogy,"Thu, 13 Dec 2018 03:31:11 GMT",BI Data Analyst,"Westlake, TX",,https://www.careerjet.com/job/b7096e743e5951bdb1a4f268c9d9949a.html,"[sql, excel, word, crm, oracle, big data, model, sales, business, masters, master, degree, sap]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
26,Robert Half,"Thu, 13 Dec 2018 02:44:26 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,https://www.careerjet.com/job/cfe4cc5509c5a470521d248bd534db32.html,"[excel, sales, business, bachelor, degree, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
27,North Texas LEAD,"Thu, 13 Dec 2018 00:48:22 GMT",IT Business Systems Data Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/35a13e7b1b191d3efc13b80b8f512156.html,"[sql, excel, microsoft office, computer science, business, operation, bachelor, degree]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
28,CVS Health,"Thu, 13 Dec 2018 00:15:48 GMT",Sr Analyst Data Warehouse,"Richardson, TX",,https://www.careerjet.com/job/3b5656afe42d2602b51f15fe4e386719.html,"[python, excel, enterprise, big data, computer science, business, bachelor, degree, 3]",0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0
29,Chevron,"Wed, 12 Dec 2018 23:54:57 GMT",S&T- Market Data Analyst,"Houston, TX",,https://www.careerjet.com/job/8a6cd08d613a79ce6766c9961804136c.html,"[business, bachelor, degree, 8]",0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,Cenpatico,"Sat, 08 Dec 2018 08:14:59 GMT",Business Analyst II(Healthcare Data,"Austin, TX",,https://www.careerjet.com/job/bff6ad4c48679b97d7e0cd3da23bc717.html,"[sql, excel, healthcare, business, operation, bachelor, degree, 4]",0,1,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,0
51,Cheniere,"Sat, 08 Dec 2018 07:17:38 GMT",Health and Safety Data Analyst,"Houston, TX",,https://www.careerjet.com/job/fe3e5e4701057eda33528c26757cdfdf.html,"[excel, microsoft office, enterprise, business, operation, bachelor, degree, ]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,0
52,,"Sat, 08 Dec 2018 01:25:54 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/cf91099fed241f07d51ec9dafed501aa.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
53,Robert Half,"Sat, 08 Dec 2018 00:13:30 GMT",Data Analyst,"San Antonio, TX",$25 - 27 per hour,https://www.careerjet.com/job/9d89c5b04bedd12ae4c24cc278ca7886.html,"[excel, word, oracle, finance, accounting, master, sap]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
54,Textron,"Sat, 08 Dec 2018 00:10:22 GMT",Data Analyst (V-247Program),"Fort Worth, TX",,https://www.careerjet.com/job/94a74f362462282297db8b3e9536d475.html,"[excel, finance, accounting, business, bachelor, degree, sap, ms, 2]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
55,Saxon Global,"Fri, 07 Dec 2018 23:52:58 GMT","Senior Data Analyst Developer (SSIS, SSRS)","San Antonio, TX",,https://www.careerjet.com/job/e7895c514f0ab58aa35e9e3ac86369be.html,[],0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
56,Princeton Information,"Fri, 07 Dec 2018 23:51:06 GMT",Data Analyst - III,"Dallas, TX",$48.64 - 65.67 per hour,https://www.careerjet.com/job/66b564baf28e500c88eb15f18b818229.html,"[sql, tableau, word, big data, statistics, economics, model, modeling, business, bachelor, master, degree, 5]",0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
57,CornerStone Staffing,"Fri, 07 Dec 2018 23:45:31 GMT",Data Analyst,"Richardson, TX",$24 per hour,https://www.careerjet.com/job/0a296d21088bc8c6f5b43b7fa590803a.html,"[sql, excel, word, ms, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
58,TechnipFMC,"Fri, 07 Dec 2018 23:03:43 GMT",Data Support Analyst,"Houston, TX",,https://www.careerjet.com/job/ff10336f6b5f898ba2bbc2ce5f61440c.html,"[oracle, computer science, business, ]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0
59,Advantage Resourcing,"Fri, 07 Dec 2018 08:53:33 GMT",Data Analyst,"Round Rock, TX",,https://www.careerjet.com/job/3d383317ec95a416bba3d964910a7349.html,"[tableau, excel, finance, accounting, sales]",0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
60,McKesson Technologies Limited,"Fri, 07 Dec 2018 08:50:32 GMT",Data Management Analyst,"Irving, TX",,https://www.careerjet.com/job/7fe62b912a8c652874633cc9ec74fb71.html,"[sql, excel, healthcare, business, operation, master, degree, ms, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
61,Endurix,"Fri, 07 Dec 2018 08:49:51 GMT",HR Data Analyst,"Dallas, TX",,https://www.careerjet.com/job/fd164df8f748f97ec4afdcfcfde01629.html,"[sql, excel, finance, model, business, human resources, master, degree]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
62,,"Fri, 07 Dec 2018 08:37:49 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/e2bca52a3d745f599ceb460ac512a719.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
63,EPMA,"Fri, 07 Dec 2018 08:27:22 GMT",Data Analyst,"Addison, TX",,https://www.careerjet.com/job/75ede1521a4ee84d61a78b58ff5a7f2d.html,"[excel, microsoft office, computer science, business, degree, 3]",0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0
64,Verveba Analytics,"Fri, 07 Dec 2018 08:24:26 GMT",Data Analyst/ Hadoop developer,"Richardson, TX",,https://www.careerjet.com/job/015f4650bba10c8394f017bb9809fcfb.html,"[python, cloud, big data, computer science, model, modeling, business, human resources, bachelor, degree, sas, r, java, 3]",0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0
65,Statera,"Fri, 07 Dec 2018 07:50:25 GMT",Data Analyst - CTH - Dallas,"Dallas, TX",,https://www.careerjet.com/job/34702c994b2cceca7b3a7f92437e2046.html,"[sql, excel, big data, computer science, statistics, economics, model, business, bachelor, degree, sas, 3]",0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0
66,,"Fri, 07 Dec 2018 06:29:55 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/8fd0ad47077b0885f31650dbcb2f7440.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
67,,"Fri, 07 Dec 2018 04:57:12 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/926e6ef1cb221909334d8f7009a43893.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
68,Texas A&M University,"Fri, 07 Dec 2018 04:41:44 GMT",Data Analyst,"College Station, TX",,https://www.careerjet.com/job/aa9e1faa1902dcdeac1e78b849b1ef5a.html,"[excel, word, microsoft office, bachelor, degree, 3]",0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0
69,Spectrum,"Thu, 06 Dec 2018 23:06:27 GMT",Bus Data Analyst-Call Analytic,"Austin, TX",,https://www.careerjet.com/job/f509658f5538aa61073a0008db463231.html,"[sql, word, oracle, enterprise, accounting, statistics, economics, business, operation, bachelor, degree, 3]",0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0
70,USAA,"Thu, 06 Dec 2018 08:58:51 GMT",Data Quality Analyst I,"San Antonio, TX",,https://www.careerjet.com/job/9815c57f34e7624cb0373019ff5b308d.html,"[sql, enterprise, model, business, bachelor, master, phd, degree, sas, ]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,1
71,,"Thu, 06 Dec 2018 08:55:31 GMT",TAR-Data Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/bb4ab960510cdd063f9ea0e2320b9374.html,"[sql, excel, microsoft office, business, bachelor, degree, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
72,,"Thu, 06 Dec 2018 08:49:01 GMT",Data Services Analyst,"Dallas, TX",,https://www.careerjet.com/job/6c1db282a97c7997a26b4252d79cc003.html,"[sql, finance, operation, bachelor, degree, ms, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
73,,"Thu, 06 Dec 2018 08:43:05 GMT",Data Analyst,"Frisco, TX",,https://www.careerjet.com/job/d0f0091fffdc0d3907c3221e85aca54a.html,"[sql, python, excel, microsoft office, computer science, statistics, business, operation, bachelor, degree, r, ms, java, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
74,Bank of America,"Thu, 06 Dec 2018 06:42:29 GMT",Data Analyst,"Plano, TX",,https://www.careerjet.com/job/c3cdbba9ac3e1ac26d175ed874430eae.html,"[sql, python, excel, statistics, business, degree, r, 5]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
75,,"Thu, 06 Dec 2018 01:44:20 GMT",Data / Systems Business Analyst II,"Irving, TX",,https://www.careerjet.com/job/7e151125afb3dd2662af02f556601bc3.html,"[sql, excel, word, healthcare, business, bachelor, degree, java, 3]",0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0
76,DSI Systems,"Wed, 05 Dec 2018 23:56:33 GMT",Data Analyst,"Richardson, TX",,https://www.careerjet.com/job/834de28146cf7bfd5cd8ba379c9dc48e.html,"[sql, excel, crm, sales, business, operation, bachelor, degree, 3]",0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0
77,IT Trailblazers LLC,"Wed, 05 Dec 2018 23:08:05 GMT",Senior Business Analyst Business Analyst (Data Transformation),"Plano, TX",,https://www.careerjet.com/job/aeb572b85a2dc5960fd67391479daf92.html,"[business, master]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
78,Creditserve,"Wed, 05 Dec 2018 08:59:43 GMT",Data / Business Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/66319dcf17f7a611701ee1c8b6fa505e.html,"[sql, excel, word, microsoft office, model, marketing, business, sas, 7]",0,1,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
79,Creditserve,"Wed, 05 Dec 2018 08:51:11 GMT",Data / Business Analyst,"Austin, TX",,https://www.careerjet.com/job/13b24cd13e18ee6d89bfb7cf76e92aa2.html,"[sql, excel, word, microsoft office, model, marketing, business, sas, 7]",0,1,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0

In [9]:
result1=result

result1.loc[result1.Bachelor==1, ['degree']] = 0
result1.loc[result1.Master==1, ['degree']] = 0
result1['Master_pref']=np.where((result['Bachelor']==1) & (result['Master']==1),1,0)
result1.loc[result1.Master_pref==1, ['Bachelor','Master']] = 0
result1=result1.drop(columns=['bs' , 'ba' , 'bs/ba' , 'ba/bs' , 'bachelor' , 'mba' , 'master' , 'masters' , 'ms' , 'ma' , 'phd'])
result1

,company,date,title,locations,salary,actual_link,description,revpro,sql,tableau,...,1,7,3,4,6,65,,Bachelor,Master,Master_pref
0,Alamo Drafthouse Cinemas,"Fri, 30 Nov 2018 08:10:25 GMT",Benefits Analyst,"Austin, TX",,https://www.careerjet.com/job/14b492f081cdb7f15be85ebe0ab90838.html,"[excel, accounting, food, operation, degree, ms, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
1,Direct Energy,"Thu, 13 Dec 2018 08:22:24 GMT",Senior Data Systems Analyst,"Houston, TX",,https://www.careerjet.com/job/84b6a31a6a269ca6f997f4e7def7228e.html,"[tableau, python, word, big data, computer science, statistics, model, modeling, marketing, business, logistic, bachelor, degree, r, java, 5]",0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
2,The Hunt Corporation,"Thu, 13 Dec 2018 08:58:58 GMT",Project Controls Analyst II,"Austin, TX",$100000 per year,https://www.careerjet.com/job/1c4a5837439a3551788b39d7fc93d68e.html,"[excel, word, business, bachelor, degree, r, ms, ma, 2]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
3,Ryder Logistics & Transportation,"Thu, 13 Dec 2018 08:52:22 GMT",Logistics Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/c5f1a1895a4bd1b7cf718e890230b49b.html,"[excel, word, business, logistic, operation, bachelor, degree, ms, 8]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
4,Maxim Government Services,"Thu, 06 Dec 2018 08:53:09 GMT",Board Certified Behavior Analyst BCBA,"Houston, TX",,https://www.careerjet.com/job/6652af1a4f32fd4e84a03f52abee1a44.html,"[model, healthcare, degree]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
5,Paccar,"Wed, 12 Dec 2018 08:36:21 GMT",IT Data Analyst Intern - Summer 2019 Job,"Denton, TX",,https://www.careerjet.com/job/554317ca9a128720def2a168abe27089.html,"[sql, python, excel, microsoft office, computer science, model, business, bachelor, degree, r, java]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
6,CPS Energy,"Wed, 12 Dec 2018 07:38:03 GMT",Data Engineer,"San Antonio, TX",,https://www.careerjet.com/job/90892ae46aded8abcfe4233390fc136c.html,"[sql, python, oracle, enterprise, cloud, big data, computer science, model, modeling, business, operation, human resources, bachelor, degree]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
7,NTT Data,"Thu, 13 Dec 2018 06:38:41 GMT",Clinical-Technical Help Desk Support Analyst,"Plano, TX",,https://www.careerjet.com/job/57dd18864359cd933a9dd925d258b34b.html,"[cloud, business, master, degree, 1]",0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
8,Bansar Technologies Inc,"Fri, 16 Nov 2018 08:14:29 GMT",Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/975c852d5ee3c69118c9e27d142364b0.html,"[sql, tableau, model, modeling, business]",0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
9,Bansar Technologies Inc,"Sun, 11 Nov 2018 08:52:22 GMT",Data Architect/Data Analyst,"Austin, TX",,https://www.careerjet.com/job/5293c054e9b6ff312bf0e545b45c775f.html,"[sql, oracle, model, modeling]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
10,,"Sun, 04 Nov 2018 08:40:47 GMT",Financial Analyst Lead,"Austin, TX",,https://www.careerjet.com/job/b4b9d6518853b7708d9883011f0ebc95.html,"[word, finance, accounting, model, business, operation, bachelor, master, degree, 7]",0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,1
11,Bansar Technologies Inc,"Mon, 05 Nov 2018 08:31:30 GMT",Senior Data Analyst,"Austin, TX",,https://www.careerjet.com/job/e731dd53e53b2f0dc8a73b7e14293dc4.html,"[sql, oracle]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
12,Targetbase,"Thu, 13 Dec 2018 08:21:38 GMT",Business Analyst,"Irving, TX",,https://www.careerjet.com/job/45f8e6c4843306b045c1f32b254e3be2.html,"[sql, excel, microsoft office, crm, model, modeling, marketing, sales, business, operation, bachelor, degree, 5]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
13,Targetbase,"Thu, 13 Dec 2018 08:20:15 GMT","Financial Analyst, Jr","Irving, TX",,https://www.careerjet.com/job/7f29aa140df358c273aa268b81002186.html,"[excel, microsoft office, finance, accounting, forecasting, economics, model, marketing, business, operation, bachelor, degree, ms, 3]",0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,1
14,Targetbase,"Thu, 13 Dec 2018 08:13:42 GMT","Analyst, Analytics","Irving, TX",,https://www.careerjet.com/job/1c8a6c2a4e12081438b892eca6d956dd.html,"[sql, python, excel, word, marketing, business, bachelor, masters, master, degree, sas, r, 4]",0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,1
15,NTT Data,"Wed, 21 Nov 2018 08:06:44 GMT",Senior Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/90544e861ae68a377b7a78f885b404f1.html,"[cloud, model, business, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16,NTT Data,"Wed, 21 Nov 2018 07:51:26 GMT",Senior Business Data Analyst,"Austin, TX",,https://www.careerjet.com/job/60fbf3d7f6ed89b700b32b027bfbdb85.html,"[cloud, model, business, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
17,CyberCoders,"Thu, 13 Dec 2018 08:42:26 GMT",Senior Data Analyst,"Austin, TX",$120000 - 160000 per year,https://www.careerjet.com/job/1d42686ce46ee3fd51eb15c558cd6572.html,"[tableau, excel, big data, statistics, model, modeling, business, entertainment, bachelor, degree, r, 5]",0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
18,Robert Half,"Thu, 13 Dec 2018 08:11:34 GMT",Financial Data Analyst,"Plano, TX",$18 - 19 per hour,https://www.careerjet.com/job/01cc7b4c0267710c32cd3f6fbdc97eb7.html,"[excel, word, microsoft office, finance, accounting, economics, sales, business, master, sap, 6]",0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,1,0
19,Robert Half,"Thu, 13 Dec 2018 08:10:08 GMT",Data Reporting Analyst,"Dallas, TX",,https://www.careerjet.com/job/13068bec6d53419ebe13104b4688fb95.html,"[sql, python, excel, model, modeling, marketing, business, bachelor, degree, 65]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,0,0
20,Wits Solutions Inc,"Thu, 13 Dec 2018 07:49:00 GMT",Data Scientist - Senior Analyst Consultant,"Irving, TX",,https://www.careerjet.com/job/d99deef90c5eee6a2dea1d3d79dc0b95.html,"[python, cloud, computer science, business, bachelor, degree, sas, r, ]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,0,0
21,ReqRoute,"Thu, 13 Dec 2018 06:52:35 GMT",9063 BI Data Analyst,"Plano, TX",,https://www.careerjet.com/job/04589cac227c6607a365c5ed6cc37f3e.html,"[sql, business]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
22,St Joseph Health System,"Thu, 13 Dec 2018 06:20:01 GMT",Clinical Data Analyst,"Lubbock, TX",,https://www.careerjet.com/job/37d54198098f1121c00e1b44fb011601.html,"[sql, excel, model, modeling, healthcare, business, operation, bachelor, degree, 3]",0,1,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0
23,Robert Half,"Thu, 13 Dec 2018 04:58:15 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,https://www.careerjet.com/job/01907084254c2e9f47edc3eff67468ca.html,"[excel, sales, business, bachelor, degree, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
24,Dow,"Thu, 13 Dec 2018 04:09:26 GMT",Production Data Analyst,"Texas City, TX",,https://www.careerjet.com/job/70f7e5d64607db11f9e713a86c46b12c.html,"[excel, finance, accounting, forecasting, business, operation, master, sap, 2]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
25,Atrilogy,"Thu, 13 Dec 2018 03:31:11 GMT",BI Data Analyst,"Westlake, TX",,https://www.careerjet.com/job/b7096e743e5951bdb1a4f268c9d9949a.html,"[sql, excel, word, crm, oracle, big data, model, sales, business, masters, master, degree, sap]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
26,Robert Half,"Thu, 13 Dec 2018 02:44:26 GMT",Data Analyst,"Dallas, TX",$70000 - 75000 per year,https://www.careerjet.com/job/cfe4cc5509c5a470521d248bd534db32.html,"[excel, sales, business, bachelor, degree, 5]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
27,North Texas LEAD,"Thu, 13 Dec 2018 00:48:22 GMT",IT Business Systems Data Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/35a13e7b1b191d3efc13b80b8f512156.html,"[sql, excel, microsoft office, computer science, business, operation, bachelor, degree]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
28,CVS Health,"Thu, 13 Dec 2018 00:15:48 GMT",Sr Analyst Data Warehouse,"Richardson, TX",,https://www.careerjet.com/job/3b5656afe42d2602b51f15fe4e386719.html,"[python, excel, enterprise, big data, computer science, business, bachelor, degree, 3]",0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0
29,Chevron,"Wed, 12 Dec 2018 23:54:57 GMT",S&T- Market Data Analyst,"Houston, TX",,https://www.careerjet.com/job/8a6cd08d613a79ce6766c9961804136c.html,"[business, bachelor, degree, 8]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,Cenpatico,"Sat, 08 Dec 2018 08:14:59 GMT",Business Analyst II(Healthcare Data,"Austin, TX",,https://www.careerjet.com/job/bff6ad4c48679b97d7e0cd3da23bc717.html,"[sql, excel, healthcare, business, operation, bachelor, degree, 4]",0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,0,0
51,Cheniere,"Sat, 08 Dec 2018 07:17:38 GMT",Health and Safety Data Analyst,"Houston, TX",,https://www.careerjet.com/job/fe3e5e4701057eda33528c26757cdfdf.html,"[excel, microsoft office, enterprise, business, operation, bachelor, degree, ]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,0,0
52,,"Sat, 08 Dec 2018 01:25:54 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/cf91099fed241f07d51ec9dafed501aa.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
53,Robert Half,"Sat, 08 Dec 2018 00:13:30 GMT",Data Analyst,"San Antonio, TX",$25 - 27 per hour,https://www.careerjet.com/job/9d89c5b04bedd12ae4c24cc278ca7886.html,"[excel, word, oracle, finance, accounting, master, sap]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
54,Textron,"Sat, 08 Dec 2018 00:10:22 GMT",Data Analyst (V-247Program),"Fort Worth, TX",,https://www.careerjet.com/job/94a74f362462282297db8b3e9536d475.html,"[excel, finance, accounting, business, bachelor, degree, sap, ms, 2]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
55,Saxon Global,"Fri, 07 Dec 2018 23:52:58 GMT","Senior Data Analyst Developer (SSIS, SSRS)","San Antonio, TX",,https://www.careerjet.com/job/e7895c514f0ab58aa35e9e3ac86369be.html,[],0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
56,Princeton Information,"Fri, 07 Dec 2018 23:51:06 GMT",Data Analyst - III,"Dallas, TX",$48.64 - 65.67 per hour,https://www.careerjet.com/job/66b564baf28e500c88eb15f18b818229.html,"[sql, tableau, word, big data, statistics, economics, model, modeling, business, bachelor, master, degree, 5]",0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
57,CornerStone Staffing,"Fri, 07 Dec 2018 23:45:31 GMT",Data Analyst,"Richardson, TX",$24 per hour,https://www.careerjet.com/job/0a296d21088bc8c6f5b43b7fa590803a.html,"[sql, excel, word, ms, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
58,TechnipFMC,"Fri, 07 Dec 2018 23:03:43 GMT",Data Support Analyst,"Houston, TX",,https://www.careerjet.com/job/ff10336f6b5f898ba2bbc2ce5f61440c.html,"[oracle, computer science, business, ]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0,0
59,Advantage Resourcing,"Fri, 07 Dec 2018 08:53:33 GMT",Data Analyst,"Round Rock, TX",,https://www.careerjet.com/job/3d383317ec95a416bba3d964910a7349.html,"[tableau, excel, finance, accounting, sales]",0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
60,McKesson Technologies Limited,"Fri, 07 Dec 2018 08:50:32 GMT",Data Management Analyst,"Irving, TX",,https://www.careerjet.com/job/7fe62b912a8c652874633cc9ec74fb71.html,"[sql, excel, healthcare, business, operation, master, degree, ms, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
61,Endurix,"Fri, 07 Dec 2018 08:49:51 GMT",HR Data Analyst,"Dallas, TX",,https://www.careerjet.com/job/fd164df8f748f97ec4afdcfcfde01629.html,"[sql, excel, finance, model, business, human resources, master, degree]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
62,,"Fri, 07 Dec 2018 08:37:49 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/e2bca52a3d745f599ceb460ac512a719.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
63,EPMA,"Fri, 07 Dec 2018 08:27:22 GMT",Data Analyst,"Addison, TX",,https://www.careerjet.com/job/75ede1521a4ee84d61a78b58ff5a7f2d.html,"[excel, microsoft office, computer science, business, degree, 3]",0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,0
64,Verveba Analytics,"Fri, 07 Dec 2018 08:24:26 GMT",Data Analyst/ Hadoop developer,"Richardson, TX",,https://www.careerjet.com/job/015f4650bba10c8394f017bb9809fcfb.html,"[python, cloud, big data, computer science, model, modeling, business, human resources, bachelor, degree, sas, r, java, 3]",0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0
65,Statera,"Fri, 07 Dec 2018 07:50:25 GMT",Data Analyst - CTH - Dallas,"Dallas, TX",,https://www.careerjet.com/job/34702c994b2cceca7b3a7f92437e2046.html,"[sql, excel, big data, computer science, statistics, economics, model, business, bachelor, degree, sas, 3]",0,1,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0
66,,"Fri, 07 Dec 2018 06:29:55 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/8fd0ad47077b0885f31650dbcb2f7440.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
67,,"Fri, 07 Dec 2018 04:57:12 GMT",Data Science Analyst - Strategic Data Solutions,"Austin, TX",,https://www.careerjet.com/job/926e6ef1cb221909334d8f7009a43893.html,"[sql, python, excel, big data, computer science, statistics, business, bs, ms]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
68,Texas A&M University,"Fri, 07 Dec 2018 04:41:44 GMT",Data Analyst,"College Station, TX",,https://www.careerjet.com/job/aa9e1faa1902dcdeac1e78b849b1ef5a.html,"[excel, word, microsoft office, bachelor, degree, 3]",0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0
69,Spectrum,"Thu, 06 Dec 2018 23:06:27 GMT",Bus Data Analyst-Call Analytic,"Austin, TX",,https://www.careerjet.com/job/f509658f5538aa61073a0008db463231.html,"[sql, word, oracle, enterprise, accounting, statistics, economics, business, operation, bachelor, degree, 3]",0,1,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0
70,USAA,"Thu, 06 Dec 2018 08:58:51 GMT",Data Quality Analyst I,"San Antonio, TX",,https://www.careerjet.com/job/9815c57f34e7624cb0373019ff5b308d.html,"[sql, enterprise, model, business, bachelor, master, phd, degree, sas, ]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0,1
71,,"Thu, 06 Dec 2018 08:55:31 GMT",TAR-Data Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/bb4ab960510cdd063f9ea0e2320b9374.html,"[sql, excel, microsoft office, business, bachelor, degree, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
72,,"Thu, 06 Dec 2018 08:49:01 GMT",Data Services Analyst,"Dallas, TX",,https://www.careerjet.com/job/6c1db282a97c7997a26b4252d79cc003.html,"[sql, finance, operation, bachelor, degree, ms, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
73,,"Thu, 06 Dec 2018 08:43:05 GMT",Data Analyst,"Frisco, TX",,https://www.careerjet.com/job/d0f0091fffdc0d3907c3221e85aca54a.html,"[sql, python, excel, microsoft office, computer science, statistics, business, operation, bachelor, degree, r, ms, java, 2]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
74,Bank of America,"Thu, 06 Dec 2018 06:42:29 GMT",Data Analyst,"Plano, TX",,https://www.careerjet.com/job/c3cdbba9ac3e1ac26d175ed874430eae.html,"[sql, python, excel, statistics, business, degree, r, 5]",0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
75,,"Thu, 06 Dec 2018 01:44:20 GMT",Data / Systems Business Analyst II,"Irving, TX",,https://www.careerjet.com/job/7e151125afb3dd2662af02f556601bc3.html,"[sql, excel, word, healthcare, business, bachelor, degree, java, 3]",0,1,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0
76,DSI Systems,"Wed, 05 Dec 2018 23:56:33 GMT",Data Analyst,"Richardson, TX",,https://www.careerjet.com/job/834de28146cf7bfd5cd8ba379c9dc48e.html,"[sql, excel, crm, sales, business, operation, bachelor, degree, 3]",0,1,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0
77,IT Trailblazers LLC,"Wed, 05 Dec 2018 23:08:05 GMT",Senior Business Analyst Business Analyst (Data Transformation),"Plano, TX",,https://www.careerjet.com/job/aeb572b85a2dc5960fd67391479daf92.html,"[business, master]",0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
78,Creditserve,"Wed, 05 Dec 2018 08:59:43 GMT",Data / Business Analyst,"Fort Worth, TX",,https://www.careerjet.com/job/66319dcf17f7a611701ee1c8b6fa505e.html,"[sql, excel, word, microsoft office, model, marketing, business, sas, 7]",0,1,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0
79,Creditserve,"Wed, 05 Dec 2018 08:51:11 GMT",Data / Business Analyst,"Austin, TX",,https://www.careerjet.com/job/13b24cd13e18ee6d89bfb7cf76e92aa2.html,"[sql, excel, word, microsoft office, model, marketing, business, sas, 7]",0,1,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [40]:
#Arriving at the final Data frame for analysis
writer = pd.ExcelWriter('80JobsTexas.xlsx')
result1.to_excel(writer,'Sheet1')
writer.save()

In [3]:
import matplotlib.pyplot as plt
import pandas as pd
visual_df = pd.read_excel('80JobsTexas.xlsx')